  export const FIRMWARE_RELEASE_URLS = {
    main: "https://github.com/OpenQuatt/OpenQuatt/releases/latest",
    dev: "https://github.com/OpenQuatt/OpenQuatt/releases/tag/dev-latest",
  };
  export const OFFICIAL_ESPHOME_UI_URL = "https://oi.esphome.io/v3/www.js";
  export const ENTITY_REFRESH_CONCURRENCY = 2;
  export const FAST_VIEW_ENTITY_REFRESH_CONCURRENCY = 4;
  export const TREND_HISTORY_REFRESH_INTERVAL_MS = 60000;
  export const STRATEGY_OPTION_POWER_HOUSE = "Power House";
  export const STRATEGY_OPTION_CURVE = "Water Temperature Control (heating curve)";

  export const QUICK_STEPS = [
    ["setup", "Configuratie en software-update", "Kies Single of Duo en Wi-Fi of Ethernet. OpenQuatt controleert daarna de stabiele main-release en installeert deze alleen als dat nodig is."],
    ["generation", "Kies je Quatt Hybrid", "Geef hier aan welke Quatt Hybrid je hebt. Dan zet OpenQuatt de juiste regeling klaar."],
    ["flow-source", "Flowmeting configureren", "Controleer en activeer de flowbron die bij jouw Quatt-versie en controller hoort."],
    ["thermostat-source", "Thermostaatgegevens configureren", "Leg vast waar OpenQuatt de kamertemperatuur en het kamer-setpoint samen vandaan haalt."],
    ["boiler", "Aanvullende warmtebron", "Leg vast of een aanvullende warmtebron is aangesloten en wanneer OpenQuatt die mag gebruiken.", "auxHeatSourcePresent"],
    ["strategy", "Kies de verwarmingsstrategie", "Kies hier hoe OpenQuatt je verwarming regelt. Daarna lopen we samen de belangrijkste instellingen langs."],
    ["heating", "Werk de regeling uit", "Stel nu de gekozen regeling verder in. De inhoud hieronder past zich aan aan je keuze."],
    ["flow", "Flowregeling en afstelling", "Leg daarna vast hoe de pomp geregeld moet worden en welke waarden daarbij horen. De autotune staat later onder Instellingen → Installatie → Service & commissioning."],
    ["water", "Watertemperatuur beveiligen", "Controleer de normale bovengrens en de tripgrens voor het watercircuit."],
    ["silent", "Stille uren en niveaus", "Stel daarna het stille venster en de compressorlimieten voor dag en nacht in."],
    ["usage-telemetry", "Gebruiksstatistieken", "Kies of OpenQuatt beperkte technische gebruiksstatistieken mag delen. Tijdens een nieuwe Quick Start staat delen standaard aan.", "usageTelemetryEnabled"],
    ["confirm", "Bevestigen en afronden", "Controleer nog één keer je keuzes. Met afronden markeer je Quick Start als voltooid."],
  ].map(([id, title, copy, optionalEntity], index) => ({ id, kicker: `Stap ${index + 1}`, title, copy, ...(optionalEntity ? { optionalEntity } : {}) }));

  const DOMAIN_BINARY_SENSOR = "binary_sensor";
  const DOMAIN_BUTTON = "button";
  const DOMAIN_DATETIME = "datetime";
  const DOMAIN_NUMBER = "number";
  const DOMAIN_SELECT = "select";
  const DOMAIN_SENSOR = "sensor";
  const DOMAIN_SWITCH = "switch";
  const DOMAIN_TEXT = "text";
  const DOMAIN_TEXT_SENSOR = "text_sensor";
  const DOMAIN_TIME = "time";
  const DOMAIN_UPDATE = "update";
  function createEntityDefinitions(definitions) {
    return Object.fromEntries(definitions.map(([key, domain, name, optional = true]) => [
      key,
      optional ? { domain, name, optional: true } : { domain, name },
    ]));
  }

  export const ENTITY_DEFS = createEntityDefinitions([
    ["setupComplete", DOMAIN_BINARY_SENSOR, "Setup Complete"],
    ["status", DOMAIN_BINARY_SENSOR, "Status"],
    ["firmwareUpdate", DOMAIN_UPDATE, "Firmware Update"],
    ["firmwareUpdateChannel", DOMAIN_SELECT, "Firmware Update Channel"],
    ["firmwareUpdateTarget", DOMAIN_SELECT, "Firmware Update Target"],
    ["firmwareUpdateProgress", DOMAIN_SENSOR, "Firmware Update Progress"],
    ["firmwareUpdateStatus", DOMAIN_TEXT_SENSOR, "Firmware Update Status"],
    ["firmwareTestOtaUrl", DOMAIN_TEXT, "Firmware Test OTA URL"],
    ["firmwareTestOtaMd5Url", DOMAIN_TEXT, "Firmware Test OTA MD5 URL"],
    ["firmwareTestManifestUrl", DOMAIN_TEXT, "Firmware Test Manifest URL"],
    ["checkFirmwareUpdates", DOMAIN_BUTTON, "Check Firmware Updates"],
    ["installFirmwareTestOta", DOMAIN_BUTTON, "Install Firmware Test OTA"],
    ["installFirmwareTestManifest", DOMAIN_BUTTON, "Install Firmware Test Manifest"],
    ["installFirmwareUpdateTarget", DOMAIN_BUTTON, "Install Firmware Update Target"],
    ["restartAction", DOMAIN_BUTTON, "Restart"],
    ["factoryResetButton", DOMAIN_BUTTON, "Factory reset"],
    ["uptime", DOMAIN_SENSOR, "Uptime"],
    ["uptimeRaw", DOMAIN_SENSOR, "Uptime raw"],
    ["uptimeReadable", DOMAIN_TEXT_SENSOR, "Uptime readable"],
    ["timeNowHhmm", DOMAIN_TEXT_SENSOR, "Time now (HH:MM)"],
    ["ipAddress", DOMAIN_TEXT_SENSOR, "IP Address"],
    ["wifiSsid", DOMAIN_TEXT_SENSOR, "WiFi SSID"],
    ["projectVersionText", DOMAIN_TEXT_SENSOR, "OpenQuatt Version"],
    ["releaseChannelText", DOMAIN_TEXT_SENSOR, "OpenQuatt Release Channel"],
    ["installationTopology", DOMAIN_TEXT_SENSOR, "OpenQuatt Installation Topology"],
    ["hardwareProfileText", DOMAIN_TEXT_SENSOR, "OpenQuatt Hardware Profile"],
    ["hardwareRevisionText", DOMAIN_TEXT_SENSOR, "OpenQuatt Hardware Revision"],
    ["connectionText", DOMAIN_TEXT_SENSOR, "OpenQuatt Connection"],
    ["preferredConnection", DOMAIN_SELECT, "Preferred Connection"],
    ["hp1Generation", DOMAIN_TEXT_SENSOR, "HP1 - ODU generation"],
    ["hp2Generation", DOMAIN_TEXT_SENSOR, "HP2 - ODU generation"],
    ["hp1CompressorLevelProfile", DOMAIN_TEXT_SENSOR, "HP1 - Compressor level profile"],
    ["hp2CompressorLevelProfile", DOMAIN_TEXT_SENSOR, "HP2 - Compressor level profile"],
    ["hp1GenerationVariant", DOMAIN_TEXT_SENSOR, "HP1 - ODU generation variant"],
    ["hp2GenerationVariant", DOMAIN_TEXT_SENSOR, "HP2 - ODU generation variant"],
    ["hp1CustomerModelCode", DOMAIN_TEXT_SENSOR, "HP1 - ODU customer model code"],
    ["hp2CustomerModelCode", DOMAIN_TEXT_SENSOR, "HP2 - ODU customer model code"],
    ["hp1GenerationDetect", DOMAIN_BUTTON, "HP1 - Detect ODU generation"],
    ["hp2GenerationDetect", DOMAIN_BUTTON, "HP2 - Detect ODU generation"],
    ["wifiSignal", DOMAIN_SENSOR, "WiFi Signal"],
    ["espInternalTemp", DOMAIN_SENSOR, "ESP Internal Temperature"],
    ["heapFree", DOMAIN_SENSOR, "Heap Free"],
    ["heapMinFree", DOMAIN_SENSOR, "Heap Min Free"],
    ["heapLargestBlock", DOMAIN_SENSOR, "Heap Max Block"],
    ["psramFree", DOMAIN_SENSOR, "PSRAM Free"],
    ["loopTime", DOMAIN_SENSOR, "Loop Time"],
    ["statusLedsEnabled", DOMAIN_SWITCH, "Status LEDs enabled"],
    ["usageTelemetryEnabled", DOMAIN_SWITCH, "Usage statistics"],
    ["usageTelemetryChoiceConfigured", DOMAIN_BINARY_SENSOR, "Usage statistics choice configured"],
    ["usageTelemetryInstallationId", DOMAIN_TEXT_SENSOR, "Usage statistics installation ID"],
    ["hpGeneration", DOMAIN_SELECT, "Quatt Hybrid version", false],
    ["electricalCurrentLimit", DOMAIN_NUMBER, "Electrical current limit"],
    ["strategy", DOMAIN_SELECT, "Heating Control Mode", false],
    ["openquattEnabled", DOMAIN_SWITCH, "OpenQuatt Enabled"],
    ["auxHeatSourcePresent", DOMAIN_SWITCH, "Auxiliary heat source connected"],
    ["boilerCvAssistEnabled", DOMAIN_SWITCH, "Boiler assist enabled"],
    ["boilerFaultFallbackEnabled", DOMAIN_SWITCH, "Boiler fallback on heat-pump fault"],
    ["boilerConnection", DOMAIN_SELECT, "Boiler connection"],
    ["otbConnectionAutoSelected", DOMAIN_BINARY_SENSOR, "OTB - Boiler Connection Auto-selected"],
    ["otbConnectionMismatch", DOMAIN_BINARY_SENSOR, "OTB - Boiler Connection Mismatch"],
    ["manualCoolingEnable", DOMAIN_SWITCH, "Manual Cooling Enable"],
    ["coolingScheduleStartTime", DOMAIN_TIME, "Cooling schedule start time"],
    ["coolingScheduleEndTime", DOMAIN_TIME, "Cooling schedule end time"],
    ["cicCompatibilityMode", DOMAIN_SWITCH, "CiC Compatibility Mode"],
    ["silentModeOverride", DOMAIN_SELECT, "Silent Mode Override"],
    ["controlModeOverride", DOMAIN_SELECT, "CM Override"],
    ["heatingEnableSelected", DOMAIN_BINARY_SENSOR, "Heating Enable (Selected)"],
    ["heatingEnableValid", DOMAIN_BINARY_SENSOR, "Heating Enable Valid"],
    ["heatingBlockedByThermostat", DOMAIN_BINARY_SENSOR, "Heating blocked by thermostat"],
    ["coolingEnableValid", DOMAIN_BINARY_SENSOR, "Cooling Enable Valid"],
    ["coolingEnableSelected", DOMAIN_BINARY_SENSOR, "Cooling Enable (Selected)"],
    ["coolingRequestActive", DOMAIN_BINARY_SENSOR, "Cooling Request Active"],
    ["coolingPermitted", DOMAIN_BINARY_SENSOR, "Cooling Permitted"],
    ["coolingBlockReason", DOMAIN_TEXT_SENSOR, "Cooling Block Reason"],
    ["coolingGuardMode", DOMAIN_TEXT_SENSOR, "Cooling Guard Mode"],
    ["coolingDewPointSelected", DOMAIN_SENSOR, "Cooling Dew Point (Selected)"],
    ["coolingDewPointSource", DOMAIN_SELECT, "Cooling Dew Point Source"],
    ["coolingDewPointHa", DOMAIN_SENSOR, "HA - Cooling Dew Point"],
    ["coolingDewPointHaValid", DOMAIN_BINARY_SENSOR, "HA - Cooling Dew Point Valid"],
    ["apiInputCoolingDewPoint", DOMAIN_NUMBER, "api_input_cooling_dew_point"],
    ["apiInputCoolingDewPointAge", DOMAIN_SENSOR, "API Input Cooling Dew Point Age"],
    ["apiInputCoolingDewPointValid", DOMAIN_BINARY_SENSOR, "API Input Cooling Dew Point Valid"],
    ["mqttCoolingDewPoint", DOMAIN_SENSOR, "MQTT Cooling Dew Point"],
    ["mqttCoolingDewPointAge", DOMAIN_SENSOR, "MQTT Cooling Dew Point Age"],
    ["mqttCoolingDewPointValid", DOMAIN_BINARY_SENSOR, "MQTT Cooling Dew Point Valid"],
    ["coolingMinimumSafeSupplyTemp", DOMAIN_SENSOR, "Cooling Minimum Safe Supply Temp"],
    ["coolingEffectiveMinSupplyTemp", DOMAIN_SENSOR, "Cooling Effective Minimum Supply Temp"],
    ["coolingFallbackNightMinOutdoorTemp", DOMAIN_SENSOR, "Cooling Fallback Night Minimum Outdoor Temp"],
    ["coolingFallbackMinSupplyTemp", DOMAIN_SENSOR, "Cooling Fallback Minimum Supply Temp"],
    ["coolingSupplyTarget", DOMAIN_SENSOR, "Cooling Supply Target"],
    ["coolingSupplyError", DOMAIN_SENSOR, "Cooling Supply Error"],
    ["coolingDemandRaw", DOMAIN_SENSOR, "Cooling Demand (raw)"],
    ["coolingBaseDemandRaw", DOMAIN_SENSOR, "Cooling base demand raw"],
    ["coolingLimitedDemand", DOMAIN_SENSOR, "Cooling limited demand"],
    ["coolingLimiterAllowedMax", DOMAIN_SENSOR, "Cooling limiter allowed max"],
    ["coolingBufferGapFiltered", DOMAIN_SENSOR, "Cooling buffer gap filtered"],
    ["coolingBufferGapRate", DOMAIN_SENSOR, "Cooling buffer gap rate"],
    ["coolingProjectedGap", DOMAIN_SENSOR, "Cooling projected gap"],
    ["coolingProjectionBrakeActive", DOMAIN_SENSOR, "Cooling projection brake active"],
    ["coolingDewGap", DOMAIN_SENSOR, "Cooling dew gap"],
    ["coolingStopBufferGap", DOMAIN_SENSOR, "Cooling stop buffer gap"],
    ["coolingLimiterReasonCode", DOMAIN_SENSOR, "Cooling limiter reason code"],
    ["coolingStopReasonCode", DOMAIN_SENSOR, "Cooling stop reason code"],
    ["coolingRequestReasonCode", DOMAIN_SENSOR, "Cooling request reason code"],
    ["coolingRequestHp1Level", DOMAIN_SENSOR, "Cooling request HP1 level"],
    ["coolingRequestHp2Level", DOMAIN_SENSOR, "Cooling request HP2 level"],
    ["coolingRequestOwnerHp", DOMAIN_SENSOR, "Cooling request owner HP"],
    ["coolingOwnerHp", DOMAIN_SENSOR, "Cooling owner HP"],
    ["coolingWaterCycleActive", DOMAIN_SENSOR, "Cooling water cycle active"],
    ["waterSupplySource", DOMAIN_SELECT, "Water Supply Source"],
    ["flowSource", DOMAIN_SELECT, "Flow Source"],
    ["qFlowSource", DOMAIN_SELECT, "Q Flow Source"],
    ["outdoorUnitFlowMode", DOMAIN_SELECT, "Outdoor Unit Flow Mode"],
    ["outsideTempSource", DOMAIN_SELECT, "Outside Temperature Source"],
    ["roomTempSource", DOMAIN_SELECT, "Room Temperature Source"],
    ["roomSetpointSource", DOMAIN_SELECT, "Room Setpoint Source"],
    ["externalHeatDemandSource", DOMAIN_SELECT, "External Heat Demand Source"],
    ["heatingSupplyTargetSource", DOMAIN_SELECT, "Heating Supply Target Source"],
    ["heatingEnableSource", DOMAIN_SELECT, "Heating Enable Source"],
    ["coolingEnableSource", DOMAIN_SELECT, "Cooling Enable Source"],
    ["localWaterSupplyTempSource", DOMAIN_SELECT, "Local Water Supply Temp Source"],
    ["controllerFlowMeter", DOMAIN_SELECT, "Controller Flow Meter"],
    ["customFlowMeterPulsesPerLiter", DOMAIN_NUMBER, "Custom Flow Meter Pulses Per Liter"],
    ["coolingMinimumSupplyTemp", DOMAIN_NUMBER, "Cooling Minimum Supply Temp"],
    ["coolingDemandMax", DOMAIN_NUMBER, "Cooling Demand Max"],
    ["coolingRestartMode", DOMAIN_SELECT, "Cooling Restart Mode"],
    ["coolingRestartDelta", DOMAIN_NUMBER, "Cooling Restart Delta"],
    ["coolingMinimumOffTime", DOMAIN_NUMBER, "Cooling Minimum Off Time"],
    ["coolingMinimumOffTimeRemaining", DOMAIN_SENSOR, "Cooling Minimum Off Time Remaining"],
    ["coolingStartBlockReason", DOMAIN_TEXT_SENSOR, "Cooling Start Block Reason"],
    ["coolingStartBlockRemaining", DOMAIN_SENSOR, "Cooling Start Block Remaining"],
    ["coolingPidKp", DOMAIN_NUMBER, "Cooling PID Kp"],
    ["coolingPidKi", DOMAIN_NUMBER, "Cooling PID Ki"],
    ["coolingPidKd", DOMAIN_NUMBER, "Cooling PID Kd"],
    ["coolingSafetyMargin", DOMAIN_NUMBER, "Cooling Safety Margin"],
    ["coolingRoomRequestRequired", DOMAIN_SWITCH, "Cooling Room Request Required"],
    ["coolingRequestOnDelta", DOMAIN_NUMBER, "Cooling Request On Delta"],
    ["coolingRequestOffDelta", DOMAIN_NUMBER, "Cooling Request Off Delta"],
    ["coolingWithoutDewPointMode", DOMAIN_SELECT, "Cooling Without Dew Point"],
    ["flowControlMode", DOMAIN_SELECT, "Flow Control Mode", false],
    ["flowSetpoint", DOMAIN_NUMBER, "Flow Setpoint", false],
    ["coolingFlowSetpoint", DOMAIN_NUMBER, "Cooling Flow Setpoint"],
    ["manualIpwm", DOMAIN_NUMBER, "Manual iPWM", false],
    ["flowOutputIpwm", DOMAIN_SENSOR, "Flow Output iPWM"],
    ["compressorStarts2hWarningLimit", DOMAIN_NUMBER, "Compressor starts 2h warning limit"],
    ["compressorStarts72hWarningLimit", DOMAIN_NUMBER, "Compressor starts 72h warning limit"],
    ["compressorCyclingWarning2h", DOMAIN_BINARY_SENSOR, "Compressor cycling warning 2h"],
    ["compressorCyclingWarning72h", DOMAIN_BINARY_SENSOR, "Compressor cycling warning 72h"],
    ["alternatingCompressorStartsWarning", DOMAIN_BINARY_SENSOR, "Alternating compressor starts warning"],
    ["compressorCyclingAlertLatched", DOMAIN_BINARY_SENSOR, "Compressor cycling alert latched"],
    ["compressorCyclingAlertAlternating", DOMAIN_BINARY_SENSOR, "Compressor cycling alert alternating"],
    ["compressorCyclingAlertFirstSeen", DOMAIN_SENSOR, "Compressor cycling alert first seen"],
    ["compressorCyclingAlertLastSeen", DOMAIN_SENSOR, "Compressor cycling alert last seen"],
    ["compressorCyclingAlertHp1Peak2h", DOMAIN_SENSOR, "Compressor cycling alert HP1 peak 2h"],
    ["compressorCyclingAlertHp1Peak72h", DOMAIN_SENSOR, "Compressor cycling alert HP1 peak 72h"],
    ["compressorCyclingAlertHp2Peak2h", DOMAIN_SENSOR, "Compressor cycling alert HP2 peak 2h"],
    ["compressorCyclingAlertHp2Peak72h", DOMAIN_SENSOR, "Compressor cycling alert HP2 peak 72h"],
    ["acknowledgeCompressorCyclingAlert", DOMAIN_BUTTON, "Acknowledge compressor cycling alert"],
    ["acknowledgeHpIncidents", DOMAIN_BUTTON, "Acknowledge recovered HP incidents"],
    ["hp1CompressorStarts2h", DOMAIN_SENSOR, "HP1 - Compressor starts 2h"],
    ["hp1CompressorStarts6h", DOMAIN_SENSOR, "HP1 - Compressor starts 6h"],
    ["hp1CompressorStarts24h", DOMAIN_SENSOR, "HP1 - Compressor starts 24h"],
    ["hp1CompressorStarts72h", DOMAIN_SENSOR, "HP1 - Compressor starts 72h"],
    ["hp1CompressorLastStartAge", DOMAIN_SENSOR, "HP1 - Compressor last start age"],
    ["hp1RuntimeHours", DOMAIN_SENSOR, "HP1 - Runtime Hours"],
    ["resetRuntimeCountersHp1", DOMAIN_BUTTON, "Reset Runtime Counters (HP1)"],
    ["hp2CompressorStarts2h", DOMAIN_SENSOR, "HP2 - Compressor starts 2h"],
    ["hp2CompressorStarts6h", DOMAIN_SENSOR, "HP2 - Compressor starts 6h"],
    ["hp2CompressorStarts24h", DOMAIN_SENSOR, "HP2 - Compressor starts 24h"],
    ["hp2CompressorStarts72h", DOMAIN_SENSOR, "HP2 - Compressor starts 72h"],
    ["hp2CompressorLastStartAge", DOMAIN_SENSOR, "HP2 - Compressor last start age"],
    ["hp2RuntimeHours", DOMAIN_SENSOR, "HP2 - Runtime Hours"],
    ["resetRuntimeCountersHp1Hp2", DOMAIN_BUTTON, "Reset Runtime Counters (HP1+HP2)"],
    ["runtimeLeadHp", DOMAIN_TEXT_SENSOR, "Runtime lead HP"],
    ["resetCumulativeEnergyCounters", DOMAIN_BUTTON, "Reset Cumulative Energy Counters"],
    ["lowflowFaultActive", DOMAIN_BINARY_SENSOR, "Lowflow fault active"],
    ["pt1000ReadProblem", DOMAIN_BINARY_SENSOR, "PT1000 read problem"],
    ["waterSupplyTempFallbackActive", DOMAIN_BINARY_SENSOR, "Water Supply Temp Fallback Active"],
    ["flowMismatch", DOMAIN_BINARY_SENSOR, "Flow mismatch (HP1 vs HP2)"],
    ["cicPollingEnabled", DOMAIN_SWITCH, "CIC - Enable polling"],
    ["cicFeedUrl", DOMAIN_TEXT, "CIC - Feed URL"],
    ["cicWaterSupplyTemp", DOMAIN_SENSOR, "CIC - Water Supply Temp"],
    ["cicBoilerWaterPressure", DOMAIN_SENSOR, "CIC - Boiler Water Pressure"],
    ["cicControlSetpoint", DOMAIN_SENSOR, "CIC - Control setpoint"],
    ["cicRoomSetpoint", DOMAIN_SENSOR, "CIC - Room setpoint"],
    ["cicRoomTemp", DOMAIN_SENSOR, "CIC - Room temperature"],
    ["cicFlowrate", DOMAIN_SENSOR, "CIC - Flowrate (filtered)"],
    ["cicLastSuccessAge", DOMAIN_SENSOR, "CIC - Last success age"],
    ["cicChEnabled", DOMAIN_BINARY_SENSOR, "CIC - CH enabled"],
    ["cicChEnableValid", DOMAIN_BINARY_SENSOR, "CIC - CH enable valid"],
    ["cicCoolingEnabled", DOMAIN_BINARY_SENSOR, "CIC - Cooling enabled"],
    ["cicJsonFeedOk", DOMAIN_BINARY_SENSOR, "CIC - JSON Feed OK"],
    ["cicDataStale", DOMAIN_BINARY_SENSOR, "CIC - Data stale"],
    ["otEnabled", DOMAIN_SWITCH, "OpenTherm Enabled"],
    ["otThermostatChEnable", DOMAIN_BINARY_SENSOR, "OT - Thermostat CH Enable"],
    ["otThermostatStatusValid", DOMAIN_BINARY_SENSOR, "OT - Thermostat Status Valid"],
    ["otThermostatControlSetpointValid", DOMAIN_BINARY_SENSOR, "OT - Control Setpoint Valid"],
    ["otThermostatCoolingEnable", DOMAIN_BINARY_SENSOR, "OT - Thermostat Cooling Enable"],
    ["otLinkProblem", DOMAIN_BINARY_SENSOR, "OT - Link Problem"],
    ["otControlSetpoint", DOMAIN_SENSOR, "OT - Control Setpoint"],
    ["otRoomSetpoint", DOMAIN_SENSOR, "OT - Room Setpoint"],
    ["otRoomTemp", DOMAIN_SENSOR, "OT - Room Temperature"],
    ["otbLinkAvailable", DOMAIN_BINARY_SENSOR, "OTB - Boiler Link Available"],
    ["otbChCommand", DOMAIN_SWITCH, "OTB - Central Heating Command"],
    ["otbControlSetpointCommand", DOMAIN_NUMBER, "OTB - Control Setpoint Command"],
    ["otbFaultIndication", DOMAIN_BINARY_SENSOR, "OTB - Fault Indication"],
    ["otbChActive", DOMAIN_BINARY_SENSOR, "OTB - Central Heating Active"],
    ["otbDhwActive", DOMAIN_BINARY_SENSOR, "OTB - Domestic Hot Water Active"],
    ["otbFlameOn", DOMAIN_BINARY_SENSOR, "OTB - Flame On"],
    ["otbDiagnosticIndication", DOMAIN_BINARY_SENSOR, "OTB - Diagnostic Indication"],
    ["otbDhwPresent", DOMAIN_BINARY_SENSOR, "OTB - DHW Present"],
    ["otbServiceRequest", DOMAIN_BINARY_SENSOR, "OTB - Service Required"],
    ["otbLockoutReset", DOMAIN_BINARY_SENSOR, "OTB - Lockout Reset"],
    ["otbLowWaterPressure", DOMAIN_BINARY_SENSOR, "OTB - Low Water Pressure"],
    ["otbFlameFault", DOMAIN_BINARY_SENSOR, "OTB - Flame Fault"],
    ["otbAirPressureFault", DOMAIN_BINARY_SENSOR, "OTB - Air Pressure Fault"],
    ["otbWaterOverTemp", DOMAIN_BINARY_SENSOR, "OTB - Water Overtemperature"],
    ["otbRelativeModulation", DOMAIN_SENSOR, "OTB - Relative Modulation"],
    ["otbChPressure", DOMAIN_SENSOR, "OTB - CH Water Pressure"],
    ["otbBoilerWaterTemp", DOMAIN_SENSOR, "OTB - Boiler Water Temperature"],
    ["otbReturnWaterTemp", DOMAIN_SENSOR, "OTB - Return Water Temperature"],
    ["otbDhwTemp", DOMAIN_SENSOR, "OTB - Domestic Hot Water Temperature"],
    ["otbOemFaultCode", DOMAIN_SENSOR, "OTB - OEM Fault Code"],
    ["otbOemDiagnosticCode", DOMAIN_SENSOR, "OTB - OEM Diagnostic Code"],
    ["otbMaxCapacity", DOMAIN_SENSOR, "OTB - Maximum Boiler Capacity"],
    ["otbMinModulation", DOMAIN_SENSOR, "OTB - Minimum Modulation"],
    ["otbOpenThermVersion", DOMAIN_SENSOR, "OTB - OpenTherm Device Version"],
    ["otbDeviceType", DOMAIN_SENSOR, "OTB - Device Type"],
    ["otbDeviceVersion", DOMAIN_SENSOR, "OTB - Device Product Version"],
    ["otbLastResponseAge", DOMAIN_SENSOR, "OTB - Last Response Age"],
    ["otbResponseCount", DOMAIN_SENSOR, "OTB - Valid Response Count"],
    ["otbTransportErrorCount", DOMAIN_SENSOR, "OTB - Transport Error Count"],
    ["otbResponseTimeoutCount", DOMAIN_SENSOR, "OTB - Response Timeout Count"],
    ["otbLastResponseId", DOMAIN_SENSOR, "OTB - Last Response Message ID"],
    ["otbStartHandshakeState", DOMAIN_TEXT_SENSOR, "OTB - Start Handshake State"],
    ["otbStartHandshakeDetail", DOMAIN_TEXT_SENSOR, "OTB - Start Handshake Detail"],
    ["flowKp", DOMAIN_NUMBER, "Flow PI Kp"],
    ["flowKi", DOMAIN_NUMBER, "Flow PI Ki"],
    ["boilerRatedHeatPower", DOMAIN_NUMBER, "Boiler rated heat power"],
    ["boilerSupportStartThreshold", DOMAIN_NUMBER, "CM3 deficit ON threshold"],
    ["boilerSupportStopThreshold", DOMAIN_NUMBER, "CM3 deficit OFF threshold"],
    ["commissioningCm100Start", DOMAIN_BUTTON, "CM100 Start"],
    ["commissioningCm100Stop", DOMAIN_BUTTON, "CM100 Stop"],
    ["commissioningStatus", DOMAIN_TEXT_SENSOR, "Commissioning status"],
    ["cm100Active", DOMAIN_BINARY_SENSOR, "CM100 active"],
    ["boilerPowerTestStart", DOMAIN_BUTTON, "Boiler Power Test Start"],
    ["boilerPowerTestAbort", DOMAIN_BUTTON, "Boiler Power Test Abort"],
    ["boilerPowerTestApply", DOMAIN_BUTTON, "Boiler Power Test Apply"],
    ["boilerPowerTestResult", DOMAIN_SENSOR, "Boiler power test result"],
    ["boilerPowerTestConfidence", DOMAIN_SENSOR, "Boiler power test confidence"],
    ["boilerPowerTestResultQuality", DOMAIN_TEXT_SENSOR, "Boiler power test result quality"],
    ["boilerPowerTestActive", DOMAIN_BINARY_SENSOR, "Boiler power test active"],
    ["boilerPowerTestStatus", DOMAIN_TEXT_SENSOR, "Boiler power test status"],
    ["flowAutotuneStart", DOMAIN_BUTTON, "Flow Autotune Start"],
    ["flowAutotuneAbort", DOMAIN_BUTTON, "Flow Autotune Abort"],
    ["flowAutotuneApply", DOMAIN_BUTTON, "Apply Flow Autotune Kp-Ki"],
    ["flowAutotuneStatus", DOMAIN_TEXT_SENSOR, "Flow Autotune status"],
    ["flowKpSuggested", DOMAIN_NUMBER, "Flow Autotune Kp suggested"],
    ["flowKiSuggested", DOMAIN_NUMBER, "Flow Autotune Ki suggested"],
    ["airPurgeStart", DOMAIN_BUTTON, "Air Purge Start"],
    ["airPurgeAbort", DOMAIN_BUTTON, "Air Purge Abort"],
    ["airPurgeReturnToAuto", DOMAIN_SWITCH, "Air purge return to Auto"],
    ["airPurgeActive", DOMAIN_BINARY_SENSOR, "Air purge active"],
    ["airPurgeStatus", DOMAIN_TEXT_SENSOR, "Air purge status"],
    ["airPurgeRemaining", DOMAIN_SENSOR, "Air purge remaining"],
    ["airPurgePhase", DOMAIN_SENSOR, "Air purge phase"],
    ["airPurgeTargetIpwm", DOMAIN_SENSOR, "Air purge target iPWM"],
    ["manualFlowStart", DOMAIN_BUTTON, "Manual Flow Start"],
    ["manualFlowAbort", DOMAIN_BUTTON, "Manual Flow Abort"],
    ["manualFlowApplyHeating", DOMAIN_BUTTON, "Apply Manual Flow To Heating"],
    ["manualFlowApplyCooling", DOMAIN_BUTTON, "Apply Manual Flow To Cooling"],
    ["manualFlowActive", DOMAIN_BINARY_SENSOR, "Manual flow active"],
    ["manualFlowStatus", DOMAIN_TEXT_SENSOR, "Manual flow status"],
    ["manualFlowSetpoint", DOMAIN_NUMBER, "Manual flow service setpoint"],
    ["manualFlowTargetIpwm", DOMAIN_SENSOR, "Manual flow target iPWM"],
    ["quickFlowTest", DOMAIN_SWITCH, "Quick flow test"],
    ["manualHpStart", DOMAIN_BUTTON, "Manual HP Start"],
    ["manualHpAbort", DOMAIN_BUTTON, "Manual HP Abort"],
    ["manualHpActive", DOMAIN_BINARY_SENSOR, "Manual HP active"],
    ["manualHpStatus", DOMAIN_TEXT_SENSOR, "Manual HP status"],
    ["manualHpGuardStatus", DOMAIN_TEXT_SENSOR, "Manual HP guard status"],
    ["manualHp1Mode", DOMAIN_SELECT, "Manual HP1 service mode"],
    ["manualHp2Mode", DOMAIN_SELECT, "Manual HP2 service mode"],
    ["manualHp1Level", DOMAIN_NUMBER, "Manual HP1 compressor level"],
    ["manualHp2Level", DOMAIN_NUMBER, "Manual HP2 compressor level"],
    ["hpWaterCalibrationStart", DOMAIN_BUTTON, "HP Water Calibration Start"],
    ["hpWaterCalibrationAbort", DOMAIN_BUTTON, "HP Water Calibration Abort"],
    ["hpWaterCalibrationApply", DOMAIN_BUTTON, "Apply HP Water Calibration Offsets"],
    ["hpWaterCalibrationActive", DOMAIN_BINARY_SENSOR, "HP water calibration active"],
    ["hpWaterCalibrationStatus", DOMAIN_TEXT_SENSOR, "HP water calibration status"],
    ["hpWaterCalibrationRemaining", DOMAIN_SENSOR, "HP water calibration remaining"],
    ["hpWaterCalibrationPhase", DOMAIN_SENSOR, "HP water calibration phase"],
    ["hpWaterCalibrationSpread", DOMAIN_SENSOR, "HP water calibration spread"],
    ["hpWaterCalibrationSupplyDelta", DOMAIN_SENSOR, "HP water calibration supply delta"],
    ["hpWaterCalibrationStableProgress", DOMAIN_SENSOR, "HP water calibration stable window progress"],
    ["hpWaterCalibrationStableRequired", DOMAIN_SENSOR, "HP water calibration stable window required"],
    ["hpWaterCalibrationResultReference", DOMAIN_SENSOR, "HP water calibration result reference"],
    ["hpWaterCalibrationResultSpreadBefore", DOMAIN_SENSOR, "HP water calibration result spread before"],
    ["hpWaterCalibrationResultExpectedSpread", DOMAIN_SENSOR, "HP water calibration result expected spread"],
    ["hpWaterCalibrationResultHp1InRawAvg", DOMAIN_SENSOR, "HP water calibration result HP1 water in raw average"],
    ["hpWaterCalibrationResultHp1OutRawAvg", DOMAIN_SENSOR, "HP water calibration result HP1 water out raw average"],
    ["hpWaterCalibrationResultHp2InRawAvg", DOMAIN_SENSOR, "HP water calibration result HP2 water in raw average"],
    ["hpWaterCalibrationResultHp2OutRawAvg", DOMAIN_SENSOR, "HP water calibration result HP2 water out raw average"],
    ["hpWaterCalibrationResultSupplyRawAvg", DOMAIN_SENSOR, "HP water calibration result supply raw average"],
    ["hpWaterCalibrationResultSupplyOffset", DOMAIN_SENSOR, "HP water calibration result supply offset"],
    ["hpWaterCalibrationResultSupplySource", DOMAIN_TEXT_SENSOR, "HP water calibration result supply source"],
    ["hp1WaterInOffset", DOMAIN_NUMBER, "HP1 water in temperature offset"],
    ["hp1WaterOutOffset", DOMAIN_NUMBER, "HP1 water out temperature offset"],
    ["hp2WaterInOffset", DOMAIN_NUMBER, "HP2 water in temperature offset"],
    ["hp2WaterOutOffset", DOMAIN_NUMBER, "HP2 water out temperature offset"],
    ["waterSupplyPt1000CalibrationOffset", DOMAIN_NUMBER, "Water Supply PT1000 Calibration Offset"],
    ["waterSupplyDs18b20CalibrationOffset", DOMAIN_NUMBER, "Water Supply DS18B20 Calibration Offset"],
    ["waterSupplyCicCalibrationOffset", DOMAIN_NUMBER, "Water Supply CIC Calibration Offset"],
    ["waterSupplyHaInputCalibrationIdentity", DOMAIN_TEXT, "Water Supply HA Input Calibration Identity"],
    ["waterSupplyHaInputCalibrationOffset", DOMAIN_NUMBER, "Water Supply HA Input Calibration Offset"],
    ["hp1WaterInOffsetSuggested", DOMAIN_NUMBER, "HP calibration HP1 water in offset suggested"],
    ["hp1WaterOutOffsetSuggested", DOMAIN_NUMBER, "HP calibration HP1 water out offset suggested"],
    ["hp2WaterInOffsetSuggested", DOMAIN_NUMBER, "HP calibration HP2 water in offset suggested"],
    ["hp2WaterOutOffsetSuggested", DOMAIN_NUMBER, "HP calibration HP2 water out offset suggested"],
    ["waterSupplyCalibrationOffset", DOMAIN_NUMBER, "Water Supply Temperature Calibration Offset"],
    ["waterSupplyCalibrationOffsetSuggested", DOMAIN_NUMBER, "HP calibration supply temperature offset suggested"],
    ["waterSupplyCalibrationRequired", DOMAIN_BINARY_SENSOR, "Water Supply Temperature Calibration Required"],
    ["waterSupplyCalibrationStatus", DOMAIN_TEXT_SENSOR, "Water Supply Temperature Calibration Status"],
    ["controlModeLabel", DOMAIN_TEXT_SENSOR, "Control Mode (Label)", false],
    ["flowMode", DOMAIN_TEXT_SENSOR, "Flow Mode", false],
    ["dayMaxHz", DOMAIN_NUMBER, "Day max frequency"],
    ["silentMaxHz", DOMAIN_NUMBER, "Silent max frequency"],
    ["silentStartTime", DOMAIN_TIME, "Silent start time", false],
    ["silentEndTime", DOMAIN_TIME, "Silent end time", false],
    ["openquattResumeAt", DOMAIN_DATETIME, "OpenQuatt resume at"],
    ["maxWater", DOMAIN_NUMBER, "Maximum water temperature", false],
    ["minRuntime", DOMAIN_NUMBER, "Minimum runtime", false],
    ["totalPower", DOMAIN_SENSOR, "Total Power Input", false],
    ["heatingPowerInput", DOMAIN_SENSOR, "Heating Power Input"],
    ["coolingPowerInput", DOMAIN_SENSOR, "Cooling Power Input"],
    ["totalCop", DOMAIN_SENSOR, "Total COP", false],
    ["totalEer", DOMAIN_SENSOR, "Total EER"],
    ["totalHeat", DOMAIN_SENSOR, "Total Heat Power", false],
    ["totalCoolingPower", DOMAIN_SENSOR, "Total Cooling Power"],
    ["boilerActive", DOMAIN_BINARY_SENSOR, "Boiler active"],
    ["boilerCommandValid", DOMAIN_BINARY_SENSOR, "Boiler command valid"],
    ["boilerCommandActive", DOMAIN_BINARY_SENSOR, "Boiler command active"],
    ["boilerCommandTargetTemperature", DOMAIN_SENSOR, "Boiler command target temperature"],
    ["boilerCommandRequestedPower", DOMAIN_SENSOR, "Boiler command requested power"],
    ["boilerCommandAge", DOMAIN_SENSOR, "Boiler command age"],
    ["boilerCommandSource", DOMAIN_TEXT_SENSOR, "Boiler command source"],
    ["boilerBlockReason", DOMAIN_TEXT_SENSOR, "Boiler block reason"],
    ["boilerStartThermalGuard", DOMAIN_TEXT_SENSOR, "Boiler warm-start guard"],
    ["boilerStartThermalSafeCeiling", DOMAIN_SENSOR, "Boiler warm-start safe ceiling"],
    ["boilerHeatPower", DOMAIN_SENSOR, "Boiler Heat Power"],
    ["auxRelayFunction", DOMAIN_SELECT, "Aux Relay Function"],
    ["auxWaitForSupplyTemp", DOMAIN_SWITCH, "Aux Relay Wait For Supply Temp"],
    ["auxHeatingStartTemp", DOMAIN_NUMBER, "Aux Relay Heating Start Temp"],
    ["auxCoolingStartTemp", DOMAIN_NUMBER, "Aux Relay Cooling Start Temp"],
    ["auxTempHysteresis", DOMAIN_NUMBER, "Aux Relay Temp Hysteresis"],
    ["auxRelayActive", DOMAIN_BINARY_SENSOR, "Aux relay active"],
    ["auxRelayStatus", DOMAIN_TEXT_SENSOR, "Aux relay status"],
    ["systemHeatPower", DOMAIN_SENSOR, "System Heat Power"],
    ["flowSelected", DOMAIN_SENSOR, "Flow average (Selected)", false],
    ["flowLocal", DOMAIN_SENSOR, "Flow average (local)"],
    ["controllerFlow", DOMAIN_SENSOR, "Controller Flow"],
    ["trendHistoryEnabled", DOMAIN_SWITCH, "Trendopslag"],
    ["trendHistoryFlashEnabled", DOMAIN_SWITCH, "Trendhistorie opslaan in flash"],
    ["debugLevel", DOMAIN_SELECT, "Debug Level"],
    ["trendHistoryFlush", DOMAIN_BUTTON, "Trendhistorie nu opslaan"],
    ["decisionLogHistoryEnabled", DOMAIN_SWITCH, "Beslisloghistorie bewaren"],
    ["decisionLogHistoryFlush", DOMAIN_BUTTON, "Beslisloghistorie nu opslaan"],
    ["decisionLogHistoryClear", DOMAIN_BUTTON, "Beslisloghistorie wissen"],
    ["lifetimeEnergyHistoryEnabled", DOMAIN_SWITCH, "Lifetime energiehistorie opslaan"],
    ["lifetimeEnergyHourRetention", DOMAIN_SELECT, "Uurdetail bewaren"],
    ["lifetimeEnergyHistoryCapture", DOMAIN_BUTTON, "Lifetime energiehistorie nu opslaan"],
    ["lifetimeEnergyHistoryClear", DOMAIN_BUTTON, "Lifetime energiehistorie wissen"],
    ["electricalEnergyDaily", DOMAIN_SENSOR, "Electrical Energy Daily"],
    ["electricalEnergyCumulative", DOMAIN_SENSOR, "Electrical Energy Cumulative"],
    ["heatingElectricalEnergyDaily", DOMAIN_SENSOR, "Heating Electrical Energy Daily"],
    ["heatingElectricalEnergyCumulative", DOMAIN_SENSOR, "Heating Electrical Energy Cumulative"],
    ["coolingElectricalEnergyDaily", DOMAIN_SENSOR, "Cooling Electrical Energy Daily"],
    ["coolingElectricalEnergyCumulative", DOMAIN_SENSOR, "Cooling Electrical Energy Cumulative"],
    ["heatpumpThermalEnergyDaily", DOMAIN_SENSOR, "HeatPump Thermal Energy Daily"],
    ["heatpumpThermalEnergyCumulative", DOMAIN_SENSOR, "HeatPump Thermal Energy Cumulative"],
    ["heatpumpCoolingEnergyDaily", DOMAIN_SENSOR, "HeatPump Cooling Energy Daily"],
    ["heatpumpCoolingEnergyCumulative", DOMAIN_SENSOR, "HeatPump Cooling Energy Cumulative"],
    ["heatpumpCopDaily", DOMAIN_SENSOR, "HeatPump COP Daily"],
    ["heatpumpCopCumulative", DOMAIN_SENSOR, "HeatPump COP Cumulative"],
    ["heatpumpEerDaily", DOMAIN_SENSOR, "HeatPump EER Daily"],
    ["heatpumpEerCumulative", DOMAIN_SENSOR, "HeatPump EER Cumulative"],
    ["boilerThermalEnergyDaily", DOMAIN_SENSOR, "Boiler Thermal Energy Daily"],
    ["boilerThermalEnergyCumulative", DOMAIN_SENSOR, "Boiler Thermal Energy Cumulative"],
    ["systemThermalEnergyDaily", DOMAIN_SENSOR, "System Thermal Energy Daily"],
    ["systemThermalEnergyCumulative", DOMAIN_SENSOR, "System Thermal Energy Cumulative"],
    ["roomTemp", DOMAIN_SENSOR, "Room Temperature (Selected)", false],
    ["roomSetpoint", DOMAIN_SENSOR, "Room Setpoint (Selected)", false],
    ["supplyTemp", DOMAIN_SENSOR, "Water Supply Temp (Selected)", false],
    ["outsideTempSelected", DOMAIN_SENSOR, "Outside Temperature (Selected)"],
    ["waterSupplyTempEsp", DOMAIN_SENSOR, "Water Supply Temp"],
    ["waterSupplyTempPt1000", DOMAIN_SENSOR, "Water Supply Temp (PT1000)"],
    ["waterSupplyTempDs18b20", DOMAIN_SENSOR, "Water Supply Temp (DS18B20)"],
    ["outsideTempLocalAggregated", DOMAIN_SENSOR, "Outside Temperature (Local aggregated)"],
    ["outsideTempHa", DOMAIN_SENSOR, "HA - Outside Temperature"],
    ["waterSupplyTempHa", DOMAIN_SENSOR, "HA - Water Supply Temperature"],
    ["roomSetpointHa", DOMAIN_SENSOR, "HA - Thermostat Setpoint"],
    ["roomTempHa", DOMAIN_SENSOR, "HA - Thermostat Room Temperature"],
    ["apiInputOutsideTemperature", DOMAIN_NUMBER, "api_input_outside_temperature"],
    ["apiInputOutsideTemperatureAge", DOMAIN_SENSOR, "API Input Outside Temperature Age"],
    ["apiInputOutsideTemperatureValid", DOMAIN_BINARY_SENSOR, "API Input Outside Temperature Valid"],
    ["mqttOutsideTemperature", DOMAIN_SENSOR, "MQTT Outside Temperature"],
    ["mqttOutsideTemperatureAge", DOMAIN_SENSOR, "MQTT Outside Temperature Age"],
    ["mqttOutsideTemperatureValid", DOMAIN_BINARY_SENSOR, "MQTT Outside Temperature Valid"],
    ["apiInputRoomTemperature", DOMAIN_NUMBER, "api_input_room_temperature"],
    ["apiInputRoomTemperatureAge", DOMAIN_SENSOR, "API Input Room Temperature Age"],
    ["apiInputRoomTemperatureValid", DOMAIN_BINARY_SENSOR, "API Input Room Temperature Valid"],
    ["mqttRoomTemperature", DOMAIN_SENSOR, "MQTT Room Temperature"],
    ["mqttRoomTemperatureAge", DOMAIN_SENSOR, "MQTT Room Temperature Age"],
    ["mqttRoomTemperatureValid", DOMAIN_BINARY_SENSOR, "MQTT Room Temperature Valid"],
    ["apiInputRoomSetpoint", DOMAIN_NUMBER, "api_input_room_setpoint"],
    ["apiInputRoomSetpointAge", DOMAIN_SENSOR, "API Input Room Setpoint Age"],
    ["apiInputRoomSetpointValid", DOMAIN_BINARY_SENSOR, "API Input Room Setpoint Valid"],
    ["mqttRoomSetpoint", DOMAIN_SENSOR, "MQTT Room Setpoint"],
    ["mqttRoomSetpointAge", DOMAIN_SENSOR, "MQTT Room Setpoint Age"],
    ["mqttRoomSetpointValid", DOMAIN_BINARY_SENSOR, "MQTT Room Setpoint Valid"],
    ["externalHeatDemandSelected", DOMAIN_SENSOR, "External Heat Demand (Selected)"],
    ["externalHeatDemandHa", DOMAIN_SENSOR, "HA - External Heat Demand"],
    ["externalHeatDemandHaValid", DOMAIN_BINARY_SENSOR, "HA - External Heat Demand Valid"],
    ["apiInputExternalHeatDemand", DOMAIN_NUMBER, "api_input_external_heat_demand"],
    ["apiInputExternalHeatDemandAge", DOMAIN_SENSOR, "API Input External Heat Demand Age"],
    ["apiInputExternalHeatDemandValid", DOMAIN_BINARY_SENSOR, "API Input External Heat Demand Valid"],
    ["heatingSupplyTargetSelected", DOMAIN_SENSOR, "Heating Supply Target (Selected)"],
    ["heatingSupplyTargetHa", DOMAIN_SENSOR, "HA - Heating Supply Target"],
    ["heatingSupplyTargetHaValid", DOMAIN_BINARY_SENSOR, "HA - Heating Supply Target Valid"],
    ["apiInputHeatingSupplyTarget", DOMAIN_NUMBER, "api_input_heating_supply_target"],
    ["apiInputHeatingSupplyTargetAge", DOMAIN_SENSOR, "API Input Heating Supply Target Age"],
    ["apiInputHeatingSupplyTargetValid", DOMAIN_BINARY_SENSOR, "API Input Heating Supply Target Valid"],
    ["mqttHeatingSupplyTarget", DOMAIN_SENSOR, "MQTT Heating Supply Target"],
    ["mqttHeatingSupplyTargetAge", DOMAIN_SENSOR, "MQTT Heating Supply Target Age"],
    ["mqttHeatingSupplyTargetValid", DOMAIN_BINARY_SENSOR, "MQTT Heating Supply Target Valid"],
    ["heatingSupplyTargetActiveSource", DOMAIN_TEXT_SENSOR, "Heating Supply – target source"],
    ["apiInputHeatingEnable", DOMAIN_SWITCH, "api_input_heating_enable"],
    ["apiInputHeatingEnableAge", DOMAIN_SENSOR, "API Input Heating Enable Age"],
    ["apiInputHeatingEnableValid", DOMAIN_BINARY_SENSOR, "API Input Heating Enable Valid"],
    ["mqttHeatingEnable", DOMAIN_BINARY_SENSOR, "MQTT Heating Enable"],
    ["mqttHeatingEnableAge", DOMAIN_SENSOR, "MQTT Heating Enable Age"],
    ["mqttHeatingEnableValid", DOMAIN_BINARY_SENSOR, "MQTT Heating Enable Valid"],
    ["apiInputCoolingEnable", DOMAIN_SWITCH, "api_input_cooling_enable"],
    ["apiInputCoolingEnableAge", DOMAIN_SENSOR, "API Input Cooling Enable Age"],
    ["apiInputCoolingEnableValid", DOMAIN_BINARY_SENSOR, "API Input Cooling Enable Valid"],
    ["mqttCoolingEnable", DOMAIN_BINARY_SENSOR, "MQTT Cooling Enable"],
    ["mqttCoolingEnableAge", DOMAIN_SENSOR, "MQTT Cooling Enable Age"],
    ["mqttCoolingEnableValid", DOMAIN_BINARY_SENSOR, "MQTT Cooling Enable Valid"],
    ["heatingEnableHa", DOMAIN_BINARY_SENSOR, "HA - Heating Enable"],
    ["coolingEnableHa", DOMAIN_BINARY_SENSOR, "HA - Cooling Enable"],
    ["outsideTempHaValid", DOMAIN_BINARY_SENSOR, "HA - Outside Temperature Valid"],
    ["waterSupplyTempHaValid", DOMAIN_BINARY_SENSOR, "HA - Water Supply Temperature Valid"],
    ["roomSetpointHaValid", DOMAIN_BINARY_SENSOR, "HA - Room Setpoint Valid"],
    ["roomTempHaValid", DOMAIN_BINARY_SENSOR, "HA - Room Temperature Valid"],
    ["heatingEnableHaValid", DOMAIN_BINARY_SENSOR, "HA - Heating Enable Valid"],
    ["coolingEnableHaValid", DOMAIN_BINARY_SENSOR, "HA - Cooling Enable Valid"],
    ["roomTempEffectiveSource", DOMAIN_TEXT_SENSOR, "Room Temperature Effective Source"],
    ["roomSetpointEffectiveSource", DOMAIN_TEXT_SENSOR, "Room Setpoint Effective Source"],
    ["waterSupplyTempEffectiveSource", DOMAIN_TEXT_SENSOR, "Water Supply Temp Effective Source"],
    ["heatingEnableEffectiveSource", DOMAIN_TEXT_SENSOR, "Heating Enable Effective Source"],
    ["coolingEnableEffectiveSource", DOMAIN_TEXT_SENSOR, "Cooling Enable Effective Source"],
    ["powerHouseDemandSource", DOMAIN_TEXT_SENSOR, "Power House – demand source"],
    ["curveSupplyTarget", DOMAIN_SENSOR, "Heating Curve Supply Target", false],
    ["requestReason", DOMAIN_TEXT_SENSOR, "Request Reason"],
    ["strategyActiveCode", DOMAIN_SENSOR, "Strategy active code"],
    ["strategyPhaseCode", DOMAIN_SENSOR, "Strategy phase code"],
    ["strategyRequestedPower", DOMAIN_SENSOR, "Strategy requested power"],
    ["strategySupplyTarget", DOMAIN_SENSOR, "Strategy supply target"],
    ["strategyWaterLimitFactor", DOMAIN_SENSOR, "Strategy water limit factor"],
    ["strategyRequestActive", DOMAIN_BINARY_SENSOR, "Strategy request active"],
    ["strategyWaterTripActive", DOMAIN_BINARY_SENSOR, "Strategy water trip active"],
    ["strategyWaterHardTripActive", DOMAIN_BINARY_SENSOR, "Strategy water hard trip active"],
    ["curveDemandEffective", DOMAIN_SENSOR, "Curve demand (effective)"],
    ["curveDemandDiscrete", DOMAIN_SENSOR, "Curve demand (discrete)"],
    ["curveDispatchTotalLevel", DOMAIN_SENSOR, "Curve dispatch total level"],
    ["curveTargetHp1Level", DOMAIN_SENSOR, "Curve target HP1 level"],
    ["curveTargetHp2Level", DOMAIN_SENSOR, "Curve target HP2 level"],
    ["curveRestartInhibit", DOMAIN_SENSOR, "Curve restart inhibit"],
    ["curveRestartBlockedByRoom", DOMAIN_SENSOR, "Curve restart blocked by room"],
    ["curvePhase", DOMAIN_TEXT_SENSOR, "Curve Phase"],
    ["curveOperatingRegime", DOMAIN_TEXT_SENSOR, "Curve operating regime"],
    ["curveCapacityMode", DOMAIN_TEXT_SENSOR, "Curve capacity mode"],
    ["hpCapacity", DOMAIN_SENSOR, "HP capacity (W)"],
    ["hpDeficit", DOMAIN_SENSOR, "HP deficit (W)"],
    ["phouseHouse", DOMAIN_SENSOR, "Power House – P_house"],
    ["phouseReq", DOMAIN_SENSOR, "Power House – P_req"],
    ["duoOptimizerReason", DOMAIN_TEXT_SENSOR, "Duo optimizer reason"],
    ["selectedInputHoldActive", DOMAIN_TEXT_SENSOR, "Selected Input Hold Active"],
    ["silentActive", DOMAIN_BINARY_SENSOR, "Silent active", false],
    ["silentStatus", DOMAIN_TEXT_SENSOR, "Silent status"],
    ["silentWindow", DOMAIN_TEXT_SENSOR, "Silent window (start-end)"],
    ["stickyActive", DOMAIN_BINARY_SENSOR, "Sticky pump active", false],
    ["housePower", DOMAIN_NUMBER, "Rated maximum house power", false],
    ["houseColdTemp", DOMAIN_NUMBER, "House cold temp", false],
    ["houseOutdoorMax", DOMAIN_NUMBER, "Maximum heating outdoor temperature", false],
    ["phResponseProfile", DOMAIN_SELECT, "Power House response profile", false],
    ["phKp", DOMAIN_NUMBER, "Power House temperature reaction", false],
    ["phComfortBelow", DOMAIN_NUMBER, "Power House comfort below setpoint", false],
    ["phComfortAbove", DOMAIN_NUMBER, "Power House comfort above setpoint", false],
    ["phDemandRiseTime", DOMAIN_NUMBER, "Power House demand rise time", false],
    ["phDemandFallTime", DOMAIN_NUMBER, "Power House demand fall time", false],
    ["lowLoadDynamicThresholds", DOMAIN_TEXT_SENSOR, "Low-load dynamic thresholds"],
    ["lowLoadDynamicOffFactor", DOMAIN_NUMBER, "Low-load dynamic OFF factor"],
    ["lowLoadDynamicOnFactor", DOMAIN_NUMBER, "Low-load dynamic ON factor"],
    ["lowLoadMinimumHysteresis", DOMAIN_NUMBER, "Low-load minimum hysteresis"],
    ["lowLoadCm2ReentryBlock", DOMAIN_NUMBER, "Low-load CM2 re-entry block"],
    ["lowLoadLatch", DOMAIN_BINARY_SENSOR, "Low-load latch"],
    ["lowLoadPminW", DOMAIN_SENSOR, "Low-load Pmin"],
    ["lowLoadOffW", DOMAIN_SENSOR, "Low-load off threshold"],
    ["lowLoadOnW", DOMAIN_SENSOR, "Low-load on threshold"],
    ["phFastIntentCode", DOMAIN_SENSOR, "Power House fast intent code"],
    ["debugStaticSnapshot", DOMAIN_TEXT_SENSOR, "Debug static snapshot"],
    ["curveControlProfile", DOMAIN_SELECT, "Heating Curve Control Profile", false],
    ["heatingCurvePidKp", DOMAIN_NUMBER, "Heating Curve PID Kp"],
    ["heatingCurvePidKi", DOMAIN_NUMBER, "Heating Curve PID Ki"],
    ["heatingCurvePidKd", DOMAIN_NUMBER, "Heating Curve PID Kd"],
    ["curveFallbackSupply", DOMAIN_NUMBER, "Curve Fallback Tsupply (No Outside Temp)", false],
    ["curveM20", DOMAIN_NUMBER, "Curve Tsupply @ -20°C", false],
    ["curveM10", DOMAIN_NUMBER, "Curve Tsupply @ -10°C", false],
    ["curve0", DOMAIN_NUMBER, "Curve Tsupply @ 0°C", false],
    ["curve5", DOMAIN_NUMBER, "Curve Tsupply @ 5°C", false],
    ["curve10", DOMAIN_NUMBER, "Curve Tsupply @ 10°C", false],
    ["curve15", DOMAIN_NUMBER, "Curve Tsupply @ 15°C", false],
    ["hp1ExcludeMinHz", DOMAIN_NUMBER, "HP1 - Excluded frequency minimum"],
    ["hp1ExcludeMaxHz", DOMAIN_NUMBER, "HP1 - Excluded frequency maximum"],
    ["hp1Power", DOMAIN_SENSOR, "HP1 - Power Input", false],
    ["hp1PowerInputQuality", DOMAIN_TEXT_SENSOR, "HP1 - Power Input quality"],
    ["hp1AcVoltage", DOMAIN_SENSOR, "HP1 - AC voltage"],
    ["hp1AcCurrent", DOMAIN_SENSOR, "HP1 - AC current"],
    ["hp1PumpPower", DOMAIN_SENSOR, "HP1 - Pump Power"],
    ["hp1PumpRelay", DOMAIN_BINARY_SENSOR, "HP1 - DC Pump Relay"],
    ["hp1Heat", DOMAIN_SENSOR, "HP1 - Heat Power", false],
    ["hp1Cooling", DOMAIN_SENSOR, "HP1 - Cooling Power", false],
    ["hp1Cop", DOMAIN_SENSOR, "HP1 - COP", false],
    ["hp1Compressor", DOMAIN_SENSOR, "HP1 compressor level"],
    ["hp1RequestedControlLevel", DOMAIN_SENSOR, "HP1 requested control level"],
    ["hp1AppliedControlLevel", DOMAIN_SENSOR, "HP1 applied control level"],
    ["hp1TableFrequency", DOMAIN_SENSOR, "HP1 table frequency"],
    ["hp1Freq", DOMAIN_SENSOR, "HP1 - Compressor frequency", false],
    ["hp1CompressorFrequencyDemand", DOMAIN_SENSOR, "HP1 - Compressor frequency demand"],
    ["hp1LowNoiseMode", DOMAIN_SELECT, "HP1 - Silent Mode"],
    ["hp1MinimumHeatingHz", DOMAIN_SENSOR, "HP1 - Minimum heating frequency"],
    ["hp1MinimumCoolingHz", DOMAIN_SENSOR, "HP1 - Minimum cooling frequency"],
    ["hp1FanSpeed", DOMAIN_SENSOR, "HP1 - Fan speed", false],
    ["hp1Flow", DOMAIN_SENSOR, "HP1 - Flow", false],
    ["hp1EvaporatorCoilTemp", DOMAIN_SENSOR, "HP1 - Evaporator coil temperature", false],
    ["hp1InnerCoilTemp", DOMAIN_SENSOR, "HP1 - Inner coil temperature", false],
    ["hp1OutsideTemp", DOMAIN_SENSOR, "HP1 - Outside temperature", false],
    ["hp1CondenserPressure", DOMAIN_SENSOR, "HP1 - Condenser pressure", false],
    ["hp1DischargeTemp", DOMAIN_SENSOR, "HP1 - Gas discharge temperature", false],
    ["hp1EvaporatorPressure", DOMAIN_SENSOR, "HP1 - Evaporator pressure", false],
    ["hp1ReturnTemp", DOMAIN_SENSOR, "HP1 - Gas return temperature", false],
    ["hp1WaterIn", DOMAIN_SENSOR, "HP1 - Water in temperature", false],
    ["hp1WaterOut", DOMAIN_SENSOR, "HP1 - Water out temperature", false],
    ["hp1WaterInRaw", DOMAIN_SENSOR, "HP1 - Water in temperature raw"],
    ["hp1WaterOutRaw", DOMAIN_SENSOR, "HP1 - Water out temperature raw"],
    ["hp1Mode", DOMAIN_TEXT_SENSOR, "HP1 - Working Mode Label", false],
    ["hp1Failures", DOMAIN_TEXT_SENSOR, "HP1 - Active Failures List", false],
    ["hp1Defrost", DOMAIN_BINARY_SENSOR, "HP1 - Defrost", false],
    ["hp1BottomPlate", DOMAIN_BINARY_SENSOR, "HP1 - Bottom plate heater", false],
    ["hp1Crankcase", DOMAIN_BINARY_SENSOR, "HP1 - Crankcase heater", false],
    ["hp1Eev", DOMAIN_SENSOR, "HP1 - EEV steps", false],
    ["hp1FourWay", DOMAIN_BINARY_SENSOR, "HP1 - 4-Way valve", false],
    ["hp2ExcludeMinHz", DOMAIN_NUMBER, "HP2 - Excluded frequency minimum"],
    ["hp2ExcludeMaxHz", DOMAIN_NUMBER, "HP2 - Excluded frequency maximum"],
    ["hp2Power", DOMAIN_SENSOR, "HP2 - Power Input"],
    ["hp2PowerInputQuality", DOMAIN_TEXT_SENSOR, "HP2 - Power Input quality"],
    ["hp2AcVoltage", DOMAIN_SENSOR, "HP2 - AC voltage"],
    ["hp2AcCurrent", DOMAIN_SENSOR, "HP2 - AC current"],
    ["hp2PumpPower", DOMAIN_SENSOR, "HP2 - Pump Power"],
    ["hp2PumpRelay", DOMAIN_BINARY_SENSOR, "HP2 - DC Pump Relay"],
    ["hp2Heat", DOMAIN_SENSOR, "HP2 - Heat Power"],
    ["hp2Cooling", DOMAIN_SENSOR, "HP2 - Cooling Power"],
    ["hp2Cop", DOMAIN_SENSOR, "HP2 - COP"],
    ["hp2Compressor", DOMAIN_SENSOR, "HP2 compressor level"],
    ["hp2RequestedControlLevel", DOMAIN_SENSOR, "HP2 requested control level"],
    ["hp2AppliedControlLevel", DOMAIN_SENSOR, "HP2 applied control level"],
    ["hp2TableFrequency", DOMAIN_SENSOR, "HP2 table frequency"],
    ["hp2Freq", DOMAIN_SENSOR, "HP2 - Compressor frequency"],
    ["hp2CompressorFrequencyDemand", DOMAIN_SENSOR, "HP2 - Compressor frequency demand"],
    ["hp2LowNoiseMode", DOMAIN_SELECT, "HP2 - Silent Mode"],
    ["hp2MinimumHeatingHz", DOMAIN_SENSOR, "HP2 - Minimum heating frequency"],
    ["hp2MinimumCoolingHz", DOMAIN_SENSOR, "HP2 - Minimum cooling frequency"],
    ["hp2FanSpeed", DOMAIN_SENSOR, "HP2 - Fan speed"],
    ["hp2Flow", DOMAIN_SENSOR, "HP2 - Flow"],
    ["hp2EvaporatorCoilTemp", DOMAIN_SENSOR, "HP2 - Evaporator coil temperature"],
    ["hp2InnerCoilTemp", DOMAIN_SENSOR, "HP2 - Inner coil temperature"],
    ["hp2OutsideTemp", DOMAIN_SENSOR, "HP2 - Outside temperature"],
    ["hp2CondenserPressure", DOMAIN_SENSOR, "HP2 - Condenser pressure"],
    ["hp2DischargeTemp", DOMAIN_SENSOR, "HP2 - Gas discharge temperature"],
    ["hp2EvaporatorPressure", DOMAIN_SENSOR, "HP2 - Evaporator pressure"],
    ["hp2ReturnTemp", DOMAIN_SENSOR, "HP2 - Gas return temperature"],
    ["hp2WaterIn", DOMAIN_SENSOR, "HP2 - Water in temperature"],
    ["hp2WaterOut", DOMAIN_SENSOR, "HP2 - Water out temperature"],
    ["hp2WaterInRaw", DOMAIN_SENSOR, "HP2 - Water in temperature raw"],
    ["hp2WaterOutRaw", DOMAIN_SENSOR, "HP2 - Water out temperature raw"],
    ["hp2Mode", DOMAIN_TEXT_SENSOR, "HP2 - Working Mode Label"],
    ["hp2Failures", DOMAIN_TEXT_SENSOR, "HP2 - Active Failures List"],
    ["hp2Defrost", DOMAIN_BINARY_SENSOR, "HP2 - Defrost"],
    ["hp2BottomPlate", DOMAIN_BINARY_SENSOR, "HP2 - Bottom plate heater"],
    ["hp2Crankcase", DOMAIN_BINARY_SENSOR, "HP2 - Crankcase heater"],
    ["hp2Eev", DOMAIN_SENSOR, "HP2 - EEV steps"],
    ["hp2FourWay", DOMAIN_BINARY_SENSOR, "HP2 - 4-Way valve"],
    ["apply", DOMAIN_BUTTON, "Complete setup", false],
    ["reset", DOMAIN_BUTTON, "Reset setup state", false],
  ]);

  export const COOLING_SCHEDULE_SOURCE_KEY = "coolingEnableSource";
  export const COOLING_SCHEDULE_VALID_KEY = "coolingEnableValid";
  export const COOLING_SCHEDULE_EFFECTIVE_SOURCE_KEY = "coolingEnableEffectiveSource";
  export const COOLING_SCHEDULE_TIME_KEYS = ["coolingScheduleStartTime", "coolingScheduleEndTime"];
  export const APP_VIEWS = [
    { id: "overview", label: "Overzicht", icon: "monitor-dashboard" },
    { id: "energy", label: "Energie", icon: "zap" },
    { id: "results", label: "Resultaten", icon: "bar-chart" },
    { id: "control", label: "Beslislog", icon: "activity", badge: "BETA" },
    { id: "diagnosis", label: "Diagnose", icon: "activity" },
    { id: "settings", label: "Instellingen", icon: "settings" },
  ];
  export const APP_VIEW_IDS = new Set(APP_VIEWS.map((view) => view.id));

  export const OQ_ICON_PATHS = {
    activity: '<path d="M3 12h4l2-7 4 14 2-7h6"/>',
    "bar-chart": '<path d="M4 19V5"/><path d="M20 19H4"/><rect x="7" y="11" width="3" height="5" rx="1"/><rect x="12" y="7" width="3" height="9" rx="1"/><rect x="17" y="3" width="3" height="13" rx="1"/>',
    calculator: '<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M8 6h8"/><path d="M16 14v4"/><path d="M16 10h.01"/><path d="M12 10h.01"/><path d="M8 10h.01"/><path d="M12 14h.01"/><path d="M8 14h.01"/><path d="M12 18h.01"/><path d="M8 18h.01"/>',
    clipboard: '<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/>',
    "clipboard-check": '<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/><path d="m11 14 2 2 4-5"/>',
    droplet: '<path d="M12 3.2s6 6.5 6 10.8a6 6 0 0 1-12 0c0-4.3 6-10.8 6-10.8z"/>',
    flame: '<path d="M12 12c2 -2.96 0 -7 -1 -8c0 3.04 -1.77 4.74 -3 6c-1.23 1.26 -2 3.24 -2 5a6 6 0 1 0 12 0c0 -1.53 -1.06 -3.94 -2 -5c-1.79 3 -2.79 3 -4 2z"/>',
    "home-cog": '<path d="M5 12h-2l9 -9l9 9h-2"/><path d="M5 12v7a2 2 0 0 0 2 2h4"/><path d="M9 21v-6a2 2 0 0 1 2 -2h1"/><circle cx="17" cy="18" r="2"/><path d="M17 14.5v1.5"/><path d="M17 20v1.5"/><path d="M13.97 16.25l1.3 .75"/><path d="M18.73 19l1.3 .75"/><path d="M20.03 16.25l-1.3 .75"/><path d="M15.27 19l-1.3 .75"/>',
    link: '<path d="M9 15l6 -6"/><path d="M11 6l.46 -.54a5 5 0 0 1 7.08 7.08l-.54 .46"/><path d="M13 18l-.46 .54a5 5 0 0 1 -7.08 -7.08l.54 -.46"/>',
    "monitor-dashboard": '<rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 20h8"/><path d="M12 16v4"/><path d="M6.5 7h7v4h-7z"/><path d="M16 7h2"/><path d="M16 10h2"/><path d="M6.5 13h3"/><path d="M11 13h2.5"/>',
    "more-horizontal": '<path d="M5 12h.01"/><path d="M12 12h.01"/><path d="M19 12h.01"/>',
    pencil: '<path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z"/>',
    settings: '<path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 1.55V21a2 2 0 1 1-4 0v-.09a1.7 1.7 0 0 0-1-1.55 1.7 1.7 0 0 0-1.88.34l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-1.55-1H3a2 2 0 1 1 0-4h.09A1.7 1.7 0 0 0 4.6 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.55V3a2 2 0 1 1 4 0v.09A1.7 1.7 0 0 0 15 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.7 1.7 0 0 0 19.4 9a1.7 1.7 0 0 0 1.55 1H21a2 2 0 1 1 0 4h-.09A1.7 1.7 0 0 0 19.4 15z"/>',
    server: '<rect x="3" y="4" width="18" height="8" rx="3"/><rect x="3" y="12" width="18" height="8" rx="3"/><path d="M7 8h.01"/><path d="M7 16h.01"/>',
    shield: '<path d="M12 3 19 6v5c0 4.4-2.8 8.4-7 10-4.2-1.6-7-5.6-7-10V6z"/><path d="m9 12 2 2 4-5"/>',
    snowflake: '<path d="M12 4v16"/><path d="M4 12h16"/><path d="m6.4 6.4 11.2 11.2"/><path d="m17.6 6.4 -11.2 11.2"/>',
    sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66 -1.41 1.41"/><path d="m19.07 4.93 -1.41 1.41"/>',
    target: '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3"/><path d="M12 19v3"/><path d="M2 12h3"/><path d="M19 12h3"/>',
    thermometer: '<path d="M14 14.76V5a2 2 0 0 0-4 0v9.76a4 4 0 1 0 4 0z"/><path d="M12 9v6"/>',
    tool: '<path d="M7 10h3v-3l-3.5 -3.5a6 6 0 0 1 8 8l6 6a2 2 0 0 1 -3 3l-6 -6a6 6 0 0 1 -8 -8z"/>',
    "triangle-alert": '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
    waves: '<path d="M3 8c1.5-1.2 3-1.2 4.5 0s3 1.2 4.5 0 3-1.2 4.5 0 3 1.2 4.5 0"/><path d="M3 13c1.5-1.2 3-1.2 4.5 0s3 1.2 4.5 0 3-1.2 4.5 0 3 1.2 4.5 0"/><path d="M3 18c1.5-1.2 3-1.2 4.5 0s3 1.2 4.5 0 3-1.2 4.5 0 3 1.2 4.5 0"/>',
    wifi: '<path d="M5 13a10 10 0 0 1 14 0"/><path d="M8.5 16.5a5 5 0 0 1 7 0"/><path d="M12 20h.01"/>',
    zap: '<path d="M13 2 4 14h7l-1 8 9-12h-7l1-8z"/>',
  };

  export function renderOqIcon(name, className = "") {
    const paths = OQ_ICON_PATHS[name];
    if (!paths) {
      return "";
    }
    const classAttr = className ? ` class="${escapeAttribute(className)}"` : "";
    return `<svg${classAttr} viewBox="0 0 24 24" aria-hidden="true" focusable="false">${paths}</svg>`;
  }

  function escapeAttribute(value) {
    return String(value)
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll("\"", "&quot;")
      .replaceAll("'", "&#39;");
  }
  export const SETTINGS_GROUPS = [
    { id: "installation", label: "Installatie", icon: "home-cog" },
    { id: "heating", label: "Verwarmen", icon: "flame" },
    { id: "cooling", label: "Koelen", icon: "snowflake" },
    { id: "integrations", label: "Bronnen / integraties", icon: "link" },
    { id: "service", label: "Service", icon: "tool" },
    { id: "system", label: "Systeem", icon: "server" },
  ];
  export const SETTINGS_GROUP_IDS = new Set(SETTINGS_GROUPS.map((group) => group.id));
  export const HP_PANEL_CONFIGS = [
    {
      title: "HP1",
      accent: "blue",
      keys: {
        power: "hp1Power",
        heat: "hp1Heat",
        cooling: "hp1Cooling",
        cop: "hp1Cop",
        compressor: "hp1Compressor",
        freq: "hp1Freq",
        fanSpeed: "hp1FanSpeed",
        flow: "hp1Flow",
        evaporatorCoilTemp: "hp1EvaporatorCoilTemp",
        innerCoilTemp: "hp1InnerCoilTemp",
        outsideTemp: "hp1OutsideTemp",
        condenserPressure: "hp1CondenserPressure",
        dischargeTemp: "hp1DischargeTemp",
        evaporatorPressure: "hp1EvaporatorPressure",
        returnTemp: "hp1ReturnTemp",
        waterIn: "hp1WaterIn",
        waterOut: "hp1WaterOut",
        mode: "hp1Mode",
        failures: "hp1Failures",
        defrost: "hp1Defrost",
        bottomPlate: "hp1BottomPlate",
        crankcase: "hp1Crankcase",
        eev: "hp1Eev",
        fourWay: "hp1FourWay",
      },
    },
    {
      title: "HP2",
      accent: "orange",
      keys: {
        power: "hp2Power",
        heat: "hp2Heat",
        cooling: "hp2Cooling",
        cop: "hp2Cop",
        compressor: "hp2Compressor",
        freq: "hp2Freq",
        fanSpeed: "hp2FanSpeed",
        flow: "hp2Flow",
        evaporatorCoilTemp: "hp2EvaporatorCoilTemp",
        innerCoilTemp: "hp2InnerCoilTemp",
        outsideTemp: "hp2OutsideTemp",
        condenserPressure: "hp2CondenserPressure",
        dischargeTemp: "hp2DischargeTemp",
        evaporatorPressure: "hp2EvaporatorPressure",
        returnTemp: "hp2ReturnTemp",
        waterIn: "hp2WaterIn",
        waterOut: "hp2WaterOut",
        mode: "hp2Mode",
        failures: "hp2Failures",
        defrost: "hp2Defrost",
        bottomPlate: "hp2BottomPlate",
        crankcase: "hp2Crankcase",
        eev: "hp2Eev",
        fourWay: "hp2FourWay",
      },
    },
  ];

  export const HP_PANEL_ENTITY_KEYS = HP_PANEL_CONFIGS.flatMap((panel) => Object.values(panel.keys));
  const HP_PANEL_METADATA_OMITTED_FIELDS = new Set(["cop", "compressor", "mode", "failures", "defrost", "bottomPlate", "crankcase", "eev", "fourWay"]);
  export const HP_PANEL_METADATA_KEYS = HP_PANEL_CONFIGS.flatMap((panel) => Object.entries(panel.keys)
    .filter(([field]) => !HP_PANEL_METADATA_OMITTED_FIELDS.has(field))
    .map(([, key]) => key));

  export const CURVE_POINTS = [
    { key: "curveM20", outdoor: -20, label: "-20°C" },
    { key: "curveM10", outdoor: -10, label: "-10°C" },
    { key: "curve0", outdoor: 0, label: "0°C" },
    { key: "curve5", outdoor: 5, label: "5°C" },
    { key: "curve10", outdoor: 10, label: "10°C" },
    { key: "curve15", outdoor: 15, label: "15°C" },
  ];

  export const POWER_HOUSE_KEYS = [
    "housePower",
    "houseColdTemp",
    "houseOutdoorMax",
    "phResponseProfile",
    "phKp",
    "phComfortBelow",
    "phComfortAbove",
    "phDemandRiseTime",
    "phDemandFallTime",
  ];
  export const FREQUENCY_CAP_KEYS = ["dayMaxHz", "silentMaxHz"];
  export const FREQUENCY_MINIMUM_KEYS = ["hp1MinimumHeatingHz", "hp1MinimumCoolingHz", "hp2MinimumHeatingHz", "hp2MinimumCoolingHz"];
  export const LIMIT_KEYS = [...FREQUENCY_CAP_KEYS, "maxWater"];
  export const FLOW_SETTING_KEYS = ["flowControlMode", "flowSetpoint", "coolingFlowSetpoint", "manualIpwm"];
  export const FLOW_TUNING_KEYS = ["flowKp", "flowKi"];
  export const SENSOR_CALIBRATION_KEYS = [
    "hp1WaterInOffset",
    "hp1WaterOutOffset",
    "hp2WaterInOffset",
    "hp2WaterOutOffset",
  ];
  export const SUPPLY_CALIBRATION_BACKUP_KEYS = [
    "waterSupplyPt1000CalibrationOffset",
    "waterSupplyDs18b20CalibrationOffset",
    "waterSupplyCicCalibrationOffset",
    "waterSupplyHaInputCalibrationIdentity",
    "waterSupplyHaInputCalibrationOffset",
  ];
  export const SENSOR_CALIBRATION_STATE_KEYS = [
    "hp1WaterInRaw",
    "hp1WaterIn",
    "hp1WaterOutRaw",
    "hp1WaterOut",
    "hp2WaterInRaw",
    "hp2WaterIn",
    "hp2WaterOutRaw",
    "hp2WaterOut",
    "waterSupplyCalibrationOffset",
    "waterSupplyCalibrationRequired",
    "waterSupplyCalibrationStatus",
  ];
  export const INSTALLATION_MONITORING_STATE_KEYS = [
    "compressorStarts2hWarningLimit",
    "compressorStarts72hWarningLimit",
    "compressorCyclingWarning2h",
    "compressorCyclingWarning72h",
    "alternatingCompressorStartsWarning",
    "compressorCyclingAlertLatched",
    "compressorCyclingAlertAlternating",
    "compressorCyclingAlertFirstSeen",
    "compressorCyclingAlertLastSeen",
    "compressorCyclingAlertHp1Peak2h",
    "compressorCyclingAlertHp1Peak72h",
    "compressorCyclingAlertHp2Peak2h",
    "compressorCyclingAlertHp2Peak72h",
    "acknowledgeCompressorCyclingAlert",
    "acknowledgeHpIncidents",
    "hp1CompressorStarts2h",
    "hp1CompressorStarts6h",
    "hp1CompressorStarts24h",
    "hp1CompressorStarts72h",
    "hp1CompressorLastStartAge",
    "hp2CompressorStarts2h",
    "hp2CompressorStarts6h",
    "hp2CompressorStarts24h",
    "hp2CompressorStarts72h",
    "hp2CompressorLastStartAge",
    "lowflowFaultActive",
    "pt1000ReadProblem",
    "waterSupplyTempFallbackActive",
    "flowMismatch",
    "boilerFaultFallbackEnabled",
    "cicPollingEnabled",
    "cicDataStale",
    "otEnabled",
    "otThermostatStatusValid",
    "otLinkProblem",
    "roomTempSource",
    "roomSetpointSource",
    "heatingEnableSource",
    COOLING_SCHEDULE_SOURCE_KEY,
    "hp1Failures",
    "hp2Failures",
  ];
  export const INSTALLATION_MONITORING_OVERVIEW_KEYS = [
    "compressorCyclingWarning2h",
    "compressorCyclingWarning72h",
    "alternatingCompressorStartsWarning",
    "compressorCyclingAlertLatched",
    "lowflowFaultActive",
    "pt1000ReadProblem",
    "waterSupplyTempFallbackActive",
    "flowMismatch",
    "cicPollingEnabled",
    "cicDataStale",
    "otEnabled",
    "otThermostatStatusValid",
    "otLinkProblem",
    "roomTempSource",
    "roomSetpointSource",
    "heatingEnableSource",
    COOLING_SCHEDULE_SOURCE_KEY,
    "hp1Failures",
    "hp2Failures",
  ];
  export const COMMISSIONING_STATE_KEYS = [
    "commissioningStatus",
    "cm100Active",
    "commissioningCm100Start",
    "commissioningCm100Stop",
    "boilerPowerTestStart",
    "boilerPowerTestAbort",
    "boilerPowerTestApply",
    "boilerPowerTestResult",
    "boilerPowerTestConfidence",
    "boilerPowerTestResultQuality",
    "boilerPowerTestActive",
    "boilerPowerTestStatus",
    "boilerHeatPower",
    "flowAutotuneStart",
    "flowAutotuneAbort",
    "flowAutotuneApply",
    "flowAutotuneStatus",
    "flowKpSuggested",
    "flowKiSuggested",
    "airPurgeStart",
    "airPurgeAbort",
    "airPurgeReturnToAuto",
    "airPurgeActive",
    "airPurgeStatus",
    "airPurgeRemaining",
    "airPurgePhase",
    "airPurgeTargetIpwm",
    "manualFlowStart",
    "manualFlowAbort",
    "manualFlowApplyHeating",
    "manualFlowApplyCooling",
    "manualFlowActive",
    "manualFlowStatus",
    "manualFlowSetpoint",
    "manualFlowTargetIpwm",
    "manualHpStart",
    "manualHpAbort",
    "manualHpActive",
    "manualHpStatus",
    "manualHpGuardStatus",
    "manualHp1Mode",
    "manualHp2Mode",
    "manualHp1Level",
    "manualHp2Level",
    "hp1CompressorLevelProfile",
    "hp2CompressorLevelProfile",
    "hpWaterCalibrationStart",
    "hpWaterCalibrationAbort",
    "hpWaterCalibrationApply",
    "hpWaterCalibrationActive",
    "hpWaterCalibrationStatus",
    "hpWaterCalibrationRemaining",
    "hpWaterCalibrationPhase",
    "hpWaterCalibrationSpread",
    "hpWaterCalibrationSupplyDelta",
    "hpWaterCalibrationStableProgress",
    "hpWaterCalibrationStableRequired",
    "hpWaterCalibrationResultReference",
    "hpWaterCalibrationResultSpreadBefore",
    "hpWaterCalibrationResultExpectedSpread",
    "hpWaterCalibrationResultHp1InRawAvg",
    "hpWaterCalibrationResultHp1OutRawAvg",
    "hpWaterCalibrationResultHp2InRawAvg",
    "hpWaterCalibrationResultHp2OutRawAvg",
    "hpWaterCalibrationResultSupplyRawAvg",
    "hpWaterCalibrationResultSupplyOffset",
    "hpWaterCalibrationResultSupplySource",
    ...SENSOR_CALIBRATION_STATE_KEYS,
    "hp1WaterInOffsetSuggested",
    "hp1WaterOutOffsetSuggested",
    "hp2WaterInOffsetSuggested",
    "hp2WaterOutOffsetSuggested",
    "waterSupplyCalibrationOffsetSuggested",
    "supplyTemp",
    "flowSelected",
    "hp1Compressor",
    "hp1Freq",
    "hp1Failures",
    "hp2Compressor",
    "hp2Freq",
    "hp2Failures",
    "hp1Mode",
    "hp2Mode",
  ];
  export const SERVICE_STATUS_ENTITY_KEYS = new Set([
    "commissioningStatus",
    "cm100Active",
    "boilerPowerTestResult",
    "boilerPowerTestConfidence",
    "boilerPowerTestResultQuality",
    "boilerPowerTestActive",
    "boilerPowerTestStatus",
    "flowAutotuneStatus",
    "flowKpSuggested",
    "flowKiSuggested",
    "airPurgeActive",
    "airPurgeStatus",
    "airPurgeRemaining",
    "airPurgePhase",
    "airPurgeTargetIpwm",
    "manualFlowActive",
    "manualFlowStatus",
    "manualFlowTargetIpwm",
    "manualHpActive",
    "manualHpStatus",
    "manualHpGuardStatus",
    "hpWaterCalibrationActive",
    "hpWaterCalibrationStatus",
    "hpWaterCalibrationRemaining",
    "hpWaterCalibrationPhase",
    "hpWaterCalibrationSpread",
    "hpWaterCalibrationSupplyDelta",
    "hpWaterCalibrationStableProgress",
    "hpWaterCalibrationStableRequired",
    "hpWaterCalibrationResultReference",
    "hpWaterCalibrationResultSpreadBefore",
    "hpWaterCalibrationResultExpectedSpread",
    "hpWaterCalibrationResultHp1InRawAvg",
    "hpWaterCalibrationResultHp1OutRawAvg",
    "hpWaterCalibrationResultHp2InRawAvg",
    "hpWaterCalibrationResultHp2OutRawAvg",
    "hpWaterCalibrationResultSupplyRawAvg",
    "hpWaterCalibrationResultSupplyOffset",
    "hpWaterCalibrationResultSupplySource",
  ]);
  export const CIC_COMPATIBILITY_KEYS = ["cicCompatibilityMode"];
  export const OPENTHERM_SETTING_KEYS = ["otEnabled", "otLinkProblem"];
  export const BOILER_SETTING_KEYS = [
    "auxHeatSourcePresent",
    "boilerConnection",
    "boilerFaultFallbackEnabled",
  ];
  export const CIC_POLLING_SETTING_KEYS = ["cicPollingEnabled", "cicFeedUrl", "cicDataStale"];
  export const OPENTHERM_DIAGNOSTIC_KEYS = [
    "otThermostatChEnable",
    "otThermostatCoolingEnable",
    "otThermostatControlSetpointValid",
    "otControlSetpoint",
    "otRoomSetpoint",
    "otRoomTemp",
  ];
  export const BOILER_DIAGNOSTIC_KEYS = [
    "boilerCommandValid",
    "boilerCommandActive",
    "boilerCommandTargetTemperature",
    "boilerCommandRequestedPower",
    "boilerCommandAge",
    "boilerCommandSource",
    "boilerBlockReason",
    "boilerStartThermalGuard",
    "boilerStartThermalSafeCeiling",
  ];
  export const OTB_DIAGNOSTIC_KEYS = [
    "otbLinkAvailable",
    "otbChCommand",
    "otbControlSetpointCommand",
    "otbFaultIndication",
    "otbChActive",
    "otbDhwActive",
    "otbFlameOn",
    "otbDiagnosticIndication",
    "otbDhwPresent",
    "otbServiceRequest",
    "otbLockoutReset",
    "otbLowWaterPressure",
    "otbFlameFault",
    "otbAirPressureFault",
    "otbWaterOverTemp",
    "otbRelativeModulation",
    "otbChPressure",
    "otbBoilerWaterTemp",
    "otbReturnWaterTemp",
    "otbDhwTemp",
    "otbOemFaultCode",
    "otbOemDiagnosticCode",
    "otbMaxCapacity",
    "otbMinModulation",
    "otbOpenThermVersion",
    "otbDeviceType",
    "otbDeviceVersion",
    "otbLastResponseAge",
    "otbResponseCount",
    "otbLastResponseId",
  ];
  export const CIC_POLLING_DIAGNOSTIC_KEYS = [
    "cicJsonFeedOk",
    "cicWaterSupplyTemp",
    "cicBoilerWaterPressure",
    "cicControlSetpoint",
    "cicRoomSetpoint",
    "cicRoomTemp",
    "cicFlowrate",
    "cicLastSuccessAge",
    "cicChEnabled",
    "cicCoolingEnabled",
  ];
  export const SENSOR_SELECTION_KEYS = [
    "waterSupplySource",
    "localWaterSupplyTempSource",
    "controllerFlowMeter",
    "customFlowMeterPulsesPerLiter",
    "flowSource",
    "qFlowSource",
    "outdoorUnitFlowMode",
    "outsideTempSource",
    "roomTempSource",
    "roomSetpointSource",
    "heatingEnableSource",
    COOLING_SCHEDULE_SOURCE_KEY,
    "coolingDewPointSource",
  ];
  export const SENSOR_SELECTION_STATE_KEYS = [
    "supplyTemp",
    "waterSupplyTempEffectiveSource",
    "waterSupplyTempEsp",
    "waterSupplyTempPt1000",
    "waterSupplyTempDs18b20",
    "waterSupplyTempHa",
    "waterSupplyTempHaValid",
    "flowSelected",
    "flowLocal",
    "controllerFlow",
    "hp1Flow",
    "hp2Flow",
    "outsideTempSelected",
    "outsideTempLocalAggregated",
    "outsideTempHa",
    "outsideTempHaValid",
    "apiInputOutsideTemperature",
    "apiInputOutsideTemperatureAge",
    "apiInputOutsideTemperatureValid",
    "mqttOutsideTemperature",
    "mqttOutsideTemperatureAge",
    "mqttOutsideTemperatureValid",
    "roomTemp",
    "roomTempEffectiveSource",
    "roomTempHa",
    "roomTempHaValid",
    "apiInputRoomTemperature",
    "apiInputRoomTemperatureAge",
    "apiInputRoomTemperatureValid",
    "mqttRoomTemperature",
    "mqttRoomTemperatureAge",
    "mqttRoomTemperatureValid",
    "roomSetpoint",
    "roomSetpointEffectiveSource",
    "roomSetpointHa",
    "roomSetpointHaValid",
    "apiInputRoomSetpoint",
    "apiInputRoomSetpointAge",
    "apiInputRoomSetpointValid",
    "mqttRoomSetpoint",
    "mqttRoomSetpointAge",
    "mqttRoomSetpointValid",
    "externalHeatDemandSource",
    "externalHeatDemandSelected",
    "externalHeatDemandHa",
    "externalHeatDemandHaValid",
    "apiInputExternalHeatDemand",
    "apiInputExternalHeatDemandAge",
    "apiInputExternalHeatDemandValid",
    "powerHouseDemandSource",
    "heatingSupplyTargetSource",
    "heatingSupplyTargetSelected",
    "heatingSupplyTargetHa",
    "heatingSupplyTargetHaValid",
    "apiInputHeatingSupplyTarget",
    "apiInputHeatingSupplyTargetAge",
    "apiInputHeatingSupplyTargetValid",
    "mqttHeatingSupplyTarget",
    "mqttHeatingSupplyTargetAge",
    "mqttHeatingSupplyTargetValid",
    "heatingSupplyTargetActiveSource",
    "otThermostatControlSetpointValid",
    "apiInputHeatingEnable",
    "apiInputHeatingEnableAge",
    "apiInputHeatingEnableValid",
    "mqttHeatingEnable",
    "mqttHeatingEnableAge",
    "mqttHeatingEnableValid",
    "heatingEnableSelected",
    "heatingEnableValid",
    "heatingBlockedByThermostat",
    "heatingEnableEffectiveSource",
    "otThermostatChEnable",
    "otThermostatStatusValid",
    "cicChEnabled",
    "cicChEnableValid",
    "heatingEnableHa",
    "heatingEnableHaValid",
    "apiInputCoolingEnable",
    "apiInputCoolingEnableAge",
    "apiInputCoolingEnableValid",
    "mqttCoolingEnable",
    "mqttCoolingEnableAge",
    "mqttCoolingEnableValid",
    COOLING_SCHEDULE_VALID_KEY,
    "coolingEnableSelected",
    COOLING_SCHEDULE_EFFECTIVE_SOURCE_KEY,
    "otThermostatCoolingEnable",
    "coolingEnableHa",
    "coolingEnableHaValid",
    "coolingDewPointSelected",
    "coolingDewPointHa",
    "coolingDewPointHaValid",
    "apiInputCoolingDewPoint",
    "apiInputCoolingDewPointAge",
    "apiInputCoolingDewPointValid",
    "mqttCoolingDewPoint",
    "mqttCoolingDewPointAge",
    "mqttCoolingDewPointValid",
  ];
  export const QUICK_START_FLOW_SOURCE_KEYS = [
    "hardwareProfileText",
    "hpGeneration",
    "flowSource",
    "qFlowSource",
    "cicPollingEnabled",
    "cicFeedUrl",
    "cicJsonFeedOk",
    "cicDataStale",
    "cicFlowrate",
    "controllerFlow",
    "flowSelected",
    "flowLocal",
    "hp1Flow",
    "hp2Flow",
    "commissioningCm100Start",
    "commissioningCm100Stop",
    "commissioningStatus",
    "cm100Active",
    "quickFlowTest",
  ];
  export const QUICK_START_THERMOSTAT_SOURCE_KEYS = [
    "hardwareProfileText",
    "roomTempSource",
    "roomSetpointSource",
    "roomTemp",
    "roomSetpoint",
    "roomTempEffectiveSource",
    "roomSetpointEffectiveSource",
    "otEnabled",
    "otLinkProblem",
    "otRoomTemp",
    "otRoomSetpoint",
    "cicPollingEnabled",
    "cicFeedUrl",
    "cicJsonFeedOk",
    "cicDataStale",
    "cicRoomTemp",
    "cicRoomSetpoint",
    "roomTempHa",
    "roomTempHaValid",
    "apiInputRoomTemperature",
    "apiInputRoomTemperatureAge",
    "apiInputRoomTemperatureValid",
    "mqttRoomTemperature",
    "mqttRoomTemperatureAge",
    "mqttRoomTemperatureValid",
    "roomSetpointHa",
    "roomSetpointHaValid",
    "apiInputRoomSetpoint",
    "apiInputRoomSetpointAge",
    "apiInputRoomSetpointValid",
    "mqttRoomSetpoint",
    "mqttRoomSetpointAge",
    "mqttRoomSetpointValid",
  ];
  export const COOLING_SETTING_KEYS = [
    ...COOLING_SCHEDULE_TIME_KEYS,
    "coolingMinimumSupplyTemp",
    "coolingDemandMax",
    "coolingRestartMode",
    "coolingRestartDelta",
    "coolingMinimumOffTime",
    "coolingPidKp",
    "coolingPidKi",
    "coolingPidKd",
    "coolingRoomRequestRequired",
    "coolingRequestOnDelta",
    "coolingRequestOffDelta",
    "coolingSafetyMargin",
    "coolingDewPointSource",
    "coolingWithoutDewPointMode",
    "coolingGuardMode",
    "coolingDewPointSelected",
    "coolingDewPointHa",
    "coolingDewPointHaValid",
    "apiInputCoolingDewPoint",
    "apiInputCoolingDewPointAge",
    "apiInputCoolingDewPointValid",
    "mqttCoolingDewPoint",
    "mqttCoolingDewPointAge",
    "mqttCoolingDewPointValid",
    "coolingFallbackNightMinOutdoorTemp",
    "coolingFallbackMinSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
  ];
  export const CURVE_SETTING_KEYS = [
    ...CURVE_POINTS.map((point) => point.key),
    "curveFallbackSupply",
    "curveControlProfile",
    "heatingCurvePidKp",
    "heatingCurvePidKi",
    "heatingCurvePidKd",
  ];
  export const EXCLUDED_FREQUENCY_KEYS = [
    "hp1ExcludeMinHz", "hp1ExcludeMaxHz", "hp2ExcludeMinHz", "hp2ExcludeMaxHz",
  ];
  export const COMPRESSOR_SETTING_KEYS = ["minRuntime", ...EXCLUDED_FREQUENCY_KEYS];
  // Restore order: gate + thresholds first, the function last, so a backup
  // restore cannot energize the relay with stale gate settings in between.
  export const AUX_RELAY_SETTING_KEYS = ["auxWaitForSupplyTemp", "auxHeatingStartTemp", "auxCoolingStartTemp", "auxTempHysteresis", "auxRelayFunction"];
  export const AUX_RELAY_STATE_KEYS = ["auxRelayActive", "auxRelayStatus"];
  export const SILENT_SETTING_KEYS = ["silentStartTime", "silentEndTime", ...FREQUENCY_CAP_KEYS];
  export const BOILER_SUPPORT_SWITCHING_KEYS = ["boilerSupportStartThreshold", "boilerSupportStopThreshold"];
  export const SERVICE_CONTROL_KEYS = [
    "controlModeOverride",
    "hp1RuntimeHours",
    "hp2RuntimeHours",
    "runtimeLeadHp",
    "resetRuntimeCountersHp1",
    "resetRuntimeCountersHp1Hp2",
  ];
  export const DEBUG_RECORDING_DURATION_OPTIONS = [
    { minutes: 15, label: "15 min" },
    { minutes: 30, label: "30 min" },
    { minutes: 60, label: "1 uur" },
  ];
  export const DEBUG_RECORDING_KEYS = [
    "projectVersionText",
    "releaseChannelText",
    "installationTopology",
    "hardwareProfileText",
    "hardwareRevisionText",
    "connectionText",
    "timeNowHhmm",
    "controlModeLabel",
    "strategy",
    "openquattEnabled",
    "manualCoolingEnable",
    "silentModeOverride",
    "outsideTempSelected",
    "roomTemp",
    "roomSetpoint",
    "supplyTemp",
    "flowSelected",
    "flowControlMode",
    "flowMode",
    "flowSetpoint",
    "coolingFlowSetpoint",
    "manualIpwm",
    "flowKp",
    "flowKi",
    "totalPower",
    "heatingPowerInput",
    "coolingPowerInput",
    "hp1Mode",
    "hp1Compressor",
    "hp1Freq",
    "hp1Flow",
    "hp1Power",
    "hp1Heat",
    "hp1Cooling",
    "hp1EvaporatorCoilTemp",
    "hp1InnerCoilTemp",
    "hp1CondenserPressure",
    "hp1EvaporatorPressure",
    "hp1WaterIn",
    "hp1WaterOut",
    "hp1Defrost",
    "hp1Failures",
    "hp2Mode",
    "hp2Compressor",
    "hp2Freq",
    "hp2Flow",
    "hp2Power",
    "hp2Heat",
    "hp2Cooling",
    "hp2EvaporatorCoilTemp",
    "hp2InnerCoilTemp",
    "hp2CondenserPressure",
    "hp2EvaporatorPressure",
    "hp2WaterIn",
    "hp2WaterOut",
    "hp2Defrost",
    "hp2Failures",
    "coolingEnableSelected",
    "coolingRequestActive",
    "coolingPermitted",
    "coolingBlockReason",
    "coolingGuardMode",
    "coolingMinimumSupplyTemp",
    "coolingSafetyMargin",
    "coolingRoomRequestRequired",
    "coolingDemandMax",
    "coolingRestartDelta",
    "coolingPidKp",
    "coolingPidKi",
    "coolingPidKd",
    "coolingDewPointSelected",
    "coolingMinimumSafeSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
    "coolingSupplyTarget",
    "coolingSupplyError",
    "coolingDemandRaw",
    "coolingBaseDemandRaw",
    "coolingLimitedDemand",
    "coolingLimiterAllowedMax",
    "coolingBufferGapFiltered",
    "coolingBufferGapRate",
    "coolingProjectedGap",
    "coolingProjectionBrakeActive",
    "coolingDewGap",
    "coolingStopBufferGap",
    "coolingLimiterReasonCode",
    "coolingStopReasonCode",
    "coolingRequestReasonCode",
    "coolingRequestHp1Level",
    "coolingRequestHp2Level",
    "coolingRequestOwnerHp",
    "coolingOwnerHp",
    "coolingWaterCycleActive",
    "requestReason",
    "strategyActiveCode",
    "strategyPhaseCode",
    "strategyRequestedPower",
    "strategySupplyTarget",
    "strategyWaterLimitFactor",
    "strategyRequestActive",
    "strategyWaterTripActive",
    "strategyWaterHardTripActive",
    "curveControlProfile",
    "heatingCurvePidKp",
    "heatingCurvePidKi",
    "heatingCurvePidKd",
    "curveSupplyTarget",
    "curveDemandEffective",
    "curveDemandDiscrete",
    "curveDispatchTotalLevel",
    "curveTargetHp1Level",
    "curveTargetHp2Level",
    "curveRestartInhibit",
    "curvePhase",
    "curveOperatingRegime",
    "curveCapacityMode",
    "phouseHouse",
    "phouseReq",
    "hpCapacity",
    "hpDeficit",
    "duoOptimizerReason",
    "selectedInputHoldActive",
    "silentActive",
    "lowLoadDynamicThresholds",
    "lowLoadDynamicOffFactor",
    "lowLoadDynamicOnFactor",
    "lowLoadMinimumHysteresis",
    "lowLoadCm2ReentryBlock",
    "lowflowFaultActive",
    "flowMismatch",
    "compressorCyclingWarning2h",
    "compressorCyclingWarning72h",
    "alternatingCompressorStartsWarning",
    "cicDataStale",
    "otLinkProblem",
    "flowOutputIpwm",
    "hp1CompressorStarts2h",
    "hp1CompressorStarts6h",
    "hp1CompressorStarts24h",
    "hp1CompressorStarts72h",
    "hp2CompressorStarts2h",
    "hp2CompressorStarts6h",
    "hp2CompressorStarts24h",
    "hp2CompressorStarts72h",
    "boilerActive",
    "boilerCommandValid",
    "boilerCommandActive",
    "boilerCommandSource",
    "boilerCommandTargetTemperature",
    "boilerBlockReason",
    "otbLinkAvailable",
    "otbChCommand",
    "otbControlSetpointCommand",
    "otbFlameOn",
    "otbLastResponseAge",
    "otbTransportErrorCount",
    "otbMaxCapacity",
    "otbMinModulation",
    "curveRestartBlockedByRoom",
    "heatingEnableSource",
    "heatingEnableValid",
    "heatingEnableSelected",
    "otThermostatStatusValid",
    "otThermostatChEnable",
    "hp1Generation",
    "hp2Generation",
    "hp1GenerationVariant",
    "hp2GenerationVariant",
    "hp1CustomerModelCode",
    "hp2CustomerModelCode",
    "externalHeatDemandSource",
    "externalHeatDemandSelected",
    "powerHouseDemandSource",
    "coolingRestartMode",
    "coolingMinimumOffTime",
    "coolingMinimumOffTimeRemaining",
    "boilerPowerTestStatus",
    "boilerCommandRequestedPower",
    "boilerHeatPower",
    "otbFaultIndication",
    "otbDhwActive",
    "otbRelativeModulation",
    "otbBoilerWaterTemp",
    "otbReturnWaterTemp",
    "otbStartHandshakeDetail",
    "boilerStartThermalGuard",
    "boilerStartThermalSafeCeiling",
    "boilerPowerTestResultQuality",
    "heatingSupplyTargetSource",
    "heatingSupplyTargetSelected",
    "heatingSupplyTargetActiveSource",
    "coolingStartBlockReason",
    "coolingStartBlockRemaining",
    "hp1RequestedControlLevel",
    "hp1AppliedControlLevel",
    "hp1TableFrequency",
    "hp2RequestedControlLevel",
    "hp2AppliedControlLevel",
    "hp2TableFrequency",
    "phFastIntentCode",
    "lowLoadLatch",
    "lowLoadPminW",
    "lowLoadOffW",
    "lowLoadOnW",
    "debugStaticSnapshot",
    "hp1CompressorFrequencyDemand",
    "hp2CompressorFrequencyDemand",
    "hp1LowNoiseMode",
    "hp2LowNoiseMode",
    "hp1PowerInputQuality",
    "hp1AcVoltage",
    "hp1AcCurrent",
    "hp1FanSpeed",
    "hp1PumpPower",
    "hp1PumpRelay",
    "hp1BottomPlate",
    "hp1Crankcase",
    "hp2PowerInputQuality",
    "hp2AcVoltage",
    "hp2AcCurrent",
    "hp2FanSpeed",
    "hp2PumpPower",
    "hp2PumpRelay",
    "hp2BottomPlate",
    "hp2Crankcase",
  ];
  export const FIRMWARE_ENTITY_KEYS = ["firmwareUpdate", "firmwareUpdateChannel", "firmwareUpdateTarget", "firmwareUpdateProgress", "firmwareUpdateStatus"];
  export const FIRMWARE_TEST_ENTITY_KEYS = ["firmwareTestManifestUrl", "installFirmwareTestManifest"];
  export const FIRMWARE_TEST_LEGACY_ENTITY_KEYS = ["firmwareTestOtaUrl", "firmwareTestOtaMd5Url", "installFirmwareTestOta"];
  export const FIRMWARE_MODAL_KEYS = [...FIRMWARE_ENTITY_KEYS, ...FIRMWARE_TEST_ENTITY_KEYS, ...FIRMWARE_TEST_LEGACY_ENTITY_KEYS, "installFirmwareUpdateTarget", "projectVersionText", "releaseChannelText", "installationTopology", "hardwareProfileText", "connectionText", "preferredConnection"];
  export const TOPOLOGY_HINT_KEYS = ["hp2ExcludeMinHz", "hp2Power", "hp2WaterOut"];
  export const HEADER_ENTITY_KEYS = [
    "status",
    "uptime",
    "uptimeReadable",
    "timeNowHhmm",
    "ipAddress",
    "wifiSsid",
    "wifiSignal",
    "installationTopology",
    "hardwareProfileText",
    "connectionText",
    "preferredConnection",
    "hpGeneration",
    "projectVersionText",
    "releaseChannelText",
    "espInternalTemp",
    "controlModeOverride",
  ];
  export const OVERVIEW_KEYS = [
    "strategy",
    "openquattEnabled",
    "usageTelemetryEnabled",
    "usageTelemetryChoiceConfigured",
    "auxHeatSourcePresent",
    "boilerCvAssistEnabled",
    "boilerConnection",
    "openquattResumeAt",
    "manualCoolingEnable",
    "silentModeOverride",
    ...COOLING_SCHEDULE_TIME_KEYS,
    COOLING_SCHEDULE_SOURCE_KEY,
    COOLING_SCHEDULE_VALID_KEY,
    "coolingEnableSelected",
    COOLING_SCHEDULE_EFFECTIVE_SOURCE_KEY,
    "coolingRequestActive",
    "coolingPermitted",
    "coolingBlockReason",
    "coolingGuardMode",
    "coolingDewPointSelected",
    "coolingMinimumSafeSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
    "coolingFallbackNightMinOutdoorTemp",
    "coolingFallbackMinSupplyTemp",
    "coolingSupplyTarget",
    "coolingSupplyError",
    "coolingDemandRaw",
    "coolingLimitedDemand",
    "coolingLimiterAllowedMax",
    "coolingLimiterReasonCode",
    "coolingStartBlockReason",
    "coolingStartBlockRemaining",
    "controlModeLabel",
    "flowMode",
    "totalPower",
    "heatingPowerInput",
    "coolingPowerInput",
    "totalCop",
    "totalEer",
    "totalHeat",
    "totalCoolingPower",
    "strategyRequestedPower",
    "phouseHouse",
    "phouseReq",
    "hpCapacity",
    "boilerActive",
    "boilerCommandValid",
    "boilerCommandActive",
    "boilerCommandTargetTemperature",
    "boilerCommandRequestedPower",
    "boilerBlockReason",
    "boilerHeatPower",
    "otbLinkAvailable",
    "otbFaultIndication",
    "otbChActive",
    "otbDhwActive",
    "otbFlameOn",
    "otbDiagnosticIndication",
    "otbRelativeModulation",
    "otbChPressure",
    "otbBoilerWaterTemp",
    "otbReturnWaterTemp",
    "otbLastResponseAge",
    "systemHeatPower",
    "electricalEnergyDaily",
    "electricalEnergyCumulative",
    "heatingElectricalEnergyDaily",
    "heatingElectricalEnergyCumulative",
    "coolingElectricalEnergyDaily",
    "coolingElectricalEnergyCumulative",
    "heatpumpThermalEnergyDaily",
    "heatpumpThermalEnergyCumulative",
    "heatpumpCoolingEnergyDaily",
    "heatpumpCoolingEnergyCumulative",
    "heatpumpCopDaily",
    "heatpumpCopCumulative",
    "heatpumpEerDaily",
    "heatpumpEerCumulative",
    "boilerThermalEnergyDaily",
    "boilerThermalEnergyCumulative",
    "systemThermalEnergyDaily",
    "systemThermalEnergyCumulative",
    "lifetimeEnergyHistoryEnabled",
    "lifetimeEnergyHourRetention",
    "flowSelected",
    "outsideTempSelected",
    "roomTemp",
    "roomSetpoint",
    "supplyTemp",
    "curveSupplyTarget",
    "silentActive",
    "stickyActive",
    ...HP_PANEL_ENTITY_KEYS,
  ];
  export const CONTROL_REPLAY_STATE_KEYS = [
    "strategyActiveCode",
    "hp1CompressorStarts24h",
    "hp2CompressorStarts24h",
    "hp1RuntimeHours",
    "hp2RuntimeHours",
  ];
  export const FAST_OVERVIEW_KEYS = [
    "strategy",
    "openquattEnabled",
    "usageTelemetryEnabled",
    "usageTelemetryChoiceConfigured",
    "auxHeatSourcePresent",
    "boilerCvAssistEnabled",
    "boilerRatedHeatPower",
    "boilerConnection",
    "boilerFaultFallbackEnabled",
    "openquattResumeAt",
    "manualCoolingEnable",
    COOLING_SCHEDULE_SOURCE_KEY,
    "coolingEnableSelected",
    COOLING_SCHEDULE_EFFECTIVE_SOURCE_KEY,
    "trendHistoryEnabled",
    "trendHistoryFlashEnabled",
    "coolingPermitted",
    "coolingRequestActive",
    "coolingBlockReason",
    "coolingStartBlockReason",
    "coolingStartBlockRemaining",
    "coolingGuardMode",
    "coolingDewPointSelected",
    "coolingEffectiveMinSupplyTemp",
    "coolingDemandRaw",
    "coolingLimitedDemand",
    "coolingLimiterAllowedMax",
    "coolingLimiterReasonCode",
    "controlModeLabel",
    "flowMode",
    "flowSelected",
    "outsideTempSelected",
    "roomTemp",
    "roomSetpoint",
    "supplyTemp",
    "curveSupplyTarget",
    "silentActive",
    "stickyActive",
    "totalPower",
    "heatingPowerInput",
    "coolingPowerInput",
    "totalHeat",
    "totalCoolingPower",
    "totalCop",
    "totalEer",
    "strategyRequestedPower",
    "phouseReq",
    "hpCapacity",
    "boilerActive",
    "boilerCommandValid",
    "boilerCommandActive",
    "boilerCommandTargetTemperature",
    "boilerCommandRequestedPower",
    "boilerBlockReason",
    "boilerHeatPower",
    "otbLinkAvailable",
    "otbFaultIndication",
    "otbChActive",
    "otbDhwActive",
    "otbFlameOn",
    "otbDiagnosticIndication",
    "otbRelativeModulation",
    "otbChPressure",
    "otbBoilerWaterTemp",
    "otbReturnWaterTemp",
    "otbLastResponseAge",
    "systemHeatPower",
    "silentModeOverride",
    ...HP_PANEL_ENTITY_KEYS,
    ...INSTALLATION_MONITORING_OVERVIEW_KEYS,
  ];
  export const OVERVIEW_METADATA_KEYS = [
    ...FREQUENCY_MINIMUM_KEYS,
    "hpGeneration",
    "boilerCvAssistEnabled",
    "boilerRatedHeatPower",
    ...BOILER_SETTING_KEYS,
    "otbConnectionAutoSelected",
    "strategy",
    ...POWER_HOUSE_KEYS,
    ...CURVE_SETTING_KEYS,
    ...FLOW_SETTING_KEYS,
    "maxWater",
    ...SILENT_SETTING_KEYS,
    ...QUICK_START_FLOW_SOURCE_KEYS,
    ...QUICK_START_THERMOSTAT_SOURCE_KEYS,
    "coolingDewPointSelected",
    "coolingMinimumSafeSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
    "coolingFallbackNightMinOutdoorTemp",
    "coolingFallbackMinSupplyTemp",
    "coolingSupplyTarget",
    "coolingSupplyError",
    "coolingDemandRaw",
    "coolingLimitedDemand",
    "coolingLimiterAllowedMax",
    "coolingLimiterReasonCode",
    "totalPower",
    "heatingPowerInput",
    "coolingPowerInput",
    "totalHeat",
    "totalCoolingPower",
    "strategyRequestedPower",
    "phouseHouse",
    "phouseReq",
    "hpCapacity",
    "boilerActive",
    ...BOILER_DIAGNOSTIC_KEYS,
    "boilerHeatPower",
    ...OTB_DIAGNOSTIC_KEYS,
    "systemHeatPower",
    "flowSelected",
    "roomTemp",
    "roomSetpoint",
    "supplyTemp",
    "curveSupplyTarget",
    ...HP_PANEL_METADATA_KEYS,
  ];
  export const OVERVIEW_ENERGY_COLUMN_CONFIGS = [
    {
      label: "Nu",
      tone: "blue",
      categories: [
        {
          title: "Verwarmen",
          tone: "orange",
          groups: [
            { title: "Warmtepomp", rows: [["Elektrisch vermogen", "heatingPowerInput"], ["Warmteafgifte", "totalHeat"], ["COP", "totalCop"]] },
            { title: "CV-ketel", rows: [["Warmteafgifte", "boilerHeatPower"]] },
            { title: "Systeem", rows: [["Warmteafgifte", "systemHeatPower"]] },
          ],
        },
        {
          title: "Koelen",
          tone: "blue",
          groups: [
            { title: "Warmtepomp", rows: [["Elektrisch vermogen", "coolingPowerInput"], ["Koelafgifte", "totalCoolingPower"], ["COP (EER)", "totalEer"]] },
          ],
        },
      ],
    },
    {
      label: "Vandaag",
      tone: "orange",
      categories: [
        {
          title: "Verwarmen",
          tone: "orange",
          groups: [
            { title: "Warmtepomp", rows: [["Elektriciteit", "heatingElectricalEnergyDaily"], ["Warmte", "heatpumpThermalEnergyDaily"], ["COP", "heatpumpCopDaily"]] },
            { title: "CV-ketel", rows: [["Warmte", "boilerThermalEnergyDaily"]] },
            { title: "Systeem", rows: [["Warmte", "systemThermalEnergyDaily"]] },
          ],
        },
        {
          title: "Koelen",
          tone: "blue",
          groups: [
            { title: "Warmtepomp", rows: [["Elektriciteit", "coolingElectricalEnergyDaily"], ["Koeling", "heatpumpCoolingEnergyDaily"], ["COP (EER)", "heatpumpEerDaily"]] },
          ],
        },
      ],
    },
    {
      label: "Cumulatief",
      tone: "green",
      counterResetKey: "resetCumulativeEnergyCounters",
      categories: [
        {
          title: "Verwarmen",
          tone: "orange",
          groups: [
            { title: "Warmtepomp", rows: [["Elektriciteit", "heatingElectricalEnergyCumulative"], ["Warmte", "heatpumpThermalEnergyCumulative"], ["COP", "heatpumpCopCumulative"]] },
            { title: "CV-ketel", rows: [["Warmte", "boilerThermalEnergyCumulative"]] },
            { title: "Systeem", rows: [["Warmte", "systemThermalEnergyCumulative"]] },
          ],
        },
        {
          title: "Koelen",
          tone: "blue",
          groups: [
            { title: "Warmtepomp", rows: [["Elektriciteit", "coolingElectricalEnergyCumulative"], ["Koeling", "heatpumpCoolingEnergyCumulative"], ["COP (EER)", "heatpumpEerCumulative"]] },
          ],
        },
      ],
    },
  ];
  export const SETTINGS_KEYS = [
    "strategy",
    "installationTopology",
    "connectionText",
    "preferredConnection",
    "hpGeneration",
    "electricalCurrentLimit",
    "openquattEnabled",
    "boilerCvAssistEnabled",
    "boilerRatedHeatPower",
    ...BOILER_SETTING_KEYS,
    ...BOILER_SUPPORT_SWITCHING_KEYS,
    ...AUX_RELAY_SETTING_KEYS,
    ...AUX_RELAY_STATE_KEYS,
    ...COMMISSIONING_STATE_KEYS,
    "manualCoolingEnable",
    "usageTelemetryEnabled",
    "usageTelemetryInstallationId",
    "silentModeOverride",
    "silentActive",
    "trendHistoryEnabled",
    "trendHistoryFlashEnabled",
    "trendHistoryFlush",
    "decisionLogHistoryEnabled",
    "decisionLogHistoryFlush",
    "decisionLogHistoryClear",
    "lifetimeEnergyHistoryEnabled",
    "lifetimeEnergyHourRetention",
    "lifetimeEnergyHistoryCapture",
    "lifetimeEnergyHistoryClear",
    ...CIC_COMPATIBILITY_KEYS,
    ...OPENTHERM_SETTING_KEYS,
    ...OPENTHERM_DIAGNOSTIC_KEYS,
    ...BOILER_DIAGNOSTIC_KEYS,
    ...OTB_DIAGNOSTIC_KEYS,
    ...CIC_POLLING_SETTING_KEYS,
    ...CIC_POLLING_DIAGNOSTIC_KEYS,
    ...SENSOR_SELECTION_KEYS,
    ...SENSOR_SELECTION_STATE_KEYS,
    ...FLOW_SETTING_KEYS,
    ...FLOW_TUNING_KEYS,
    ...SENSOR_CALIBRATION_KEYS,
    ...SUPPLY_CALIBRATION_BACKUP_KEYS,
    ...SENSOR_CALIBRATION_STATE_KEYS,
    ...INSTALLATION_MONITORING_STATE_KEYS,
    ...COOLING_SETTING_KEYS,
    ...LIMIT_KEYS,
    ...POWER_HOUSE_KEYS,
    ...CURVE_SETTING_KEYS,
    ...COMPRESSOR_SETTING_KEYS,
    ...SILENT_SETTING_KEYS,
    ...SERVICE_CONTROL_KEYS,
  ];
  export const SETTINGS_BACKUP_WRITABLE_DOMAINS = new Set(["number", "select", "switch", "text", "time", "datetime"]);
  export const SETTINGS_BACKUP_EXPECTED_EXTRA_KEYS = new Set(["setupComplete", "openquattResumeAt", "firmwareUpdateChannel"]);
  export const SETTINGS_BACKUP_EXCLUDED_KEYS = new Set([
    "installationTopology",
    "preferredConnection",
    ...COMMISSIONING_STATE_KEYS,
    "cicDataStale",
    "otLinkProblem",
    "otbChCommand",
    "otbControlSetpointCommand",
    // A live power request rather than a persisted setting: restoring it
    // would re-assert a stale demand and mark it freshly valid.
    "apiInputExternalHeatDemand",
    // A live supply-target request rather than a persisted setting: restoring
    // it would re-assert a stale target and mark it freshly valid.
    "apiInputHeatingSupplyTarget",
    "coolingGuardMode",
    "coolingFallbackNightMinOutdoorTemp",
    "coolingFallbackMinSupplyTemp",
    "coolingEffectiveMinSupplyTemp",
    "statusLedsEnabled",
    "usageTelemetryEnabled",
    "controlModeOverride",
  ]);
  // Keep this aligned with persisted UI settings. The build checks that new
  // writable settings are backed up or explicitly excluded above.
  export const SETTINGS_BACKUP_SECTIONS = [
    {
      id: "installation",
      label: "Installatie",
      keys: [
        "setupComplete",
        "hpGeneration",
        "electricalCurrentLimit",
        "boilerCvAssistEnabled",
        "boilerRatedHeatPower",
        ...BOILER_SETTING_KEYS,
        ...BOILER_SUPPORT_SWITCHING_KEYS,
        ...AUX_RELAY_SETTING_KEYS,
      ],
    },
    {
      id: "operation",
      label: "Bediening",
      keys: [
        "strategy",
        "openquattEnabled",
        "manualCoolingEnable",
        "silentModeOverride",
        "openquattResumeAt",
      ],
    },
    {
      id: "integrations",
      label: "Integraties",
      keys: [
        "otEnabled",
        "cicPollingEnabled",
        "cicFeedUrl",
        "cicCompatibilityMode",
      ],
    },
    {
      id: "sensor_sources",
      label: "Sensorbronnen",
      keys: [
        ...SENSOR_CALIBRATION_KEYS,
        ...SUPPLY_CALIBRATION_BACKUP_KEYS,
        "waterSupplySource",
        "localWaterSupplyTempSource",
        "controllerFlowMeter",
        "customFlowMeterPulsesPerLiter",
        "flowSource",
        "qFlowSource",
        "outdoorUnitFlowMode",
        "outsideTempSource",
        "roomTempSource",
        "roomSetpointSource",
        "heatingEnableSource",
        COOLING_SCHEDULE_SOURCE_KEY,
        "coolingDewPointSource",
        "externalHeatDemandSource",
        "heatingSupplyTargetSource",
        "apiInputOutsideTemperature",
        "apiInputRoomTemperature",
        "apiInputRoomSetpoint",
        "apiInputHeatingEnable",
        "apiInputCoolingEnable",
        "apiInputCoolingDewPoint",
      ],
    },
    {
      id: "comfort",
      label: "Comfort",
      keys: [
        "silentStartTime",
        "silentEndTime",
        ...FREQUENCY_CAP_KEYS,
        "maxWater",
      ],
    },
    {
      id: "heatingCurve",
      label: "Stooklijn",
      keys: [
        "curveControlProfile",
        "curveFallbackSupply",
        ...CURVE_POINTS.map((point) => point.key),
        "heatingCurvePidKp",
        "heatingCurvePidKi",
        "heatingCurvePidKd",
      ],
    },
    {
      id: "powerHouse",
      label: "Power House",
      keys: [
        "housePower",
        "houseColdTemp",
        "houseOutdoorMax",
        "phResponseProfile",
        "phKp",
        "phComfortBelow",
        "phComfortAbove",
        "phDemandRiseTime",
        "phDemandFallTime",
      ],
    },
    {
      id: "flow",
      label: "Flow",
      keys: ["flowControlMode", "flowSetpoint", "coolingFlowSetpoint", "manualIpwm", "flowKp", "flowKi"],
    },
    {
      id: "cooling",
      label: "Koeling",
      keys: [
        ...COOLING_SCHEDULE_TIME_KEYS,
        "coolingMinimumSupplyTemp",
        "coolingDemandMax",
        "coolingRestartMode",
        "coolingRestartDelta",
        "coolingMinimumOffTime",
        "coolingPidKp",
        "coolingPidKi",
        "coolingPidKd",
        "coolingRoomRequestRequired",
        "coolingRequestOnDelta",
        "coolingRequestOffDelta",
        "coolingSafetyMargin",
        "coolingWithoutDewPointMode",
      ],
    },
    {
      id: "compressor",
      label: "Compressor",
      keys: ["minRuntime", "compressorStarts2hWarningLimit", "compressorStarts72hWarningLimit", ...EXCLUDED_FREQUENCY_KEYS],
    },
    {
      id: "system",
      label: "Systeem",
      keys: [
        "trendHistoryEnabled",
        "trendHistoryFlashEnabled",
        "decisionLogHistoryEnabled",
        "lifetimeEnergyHistoryEnabled",
        "lifetimeEnergyHourRetention",
        "firmwareUpdateChannel",
      ],
    },
  ];
  export const SETTINGS_BACKUP_SCHEMA_VERSION = 3;
  export const SETTINGS_BACKUP_KEYS = [...new Set(SETTINGS_BACKUP_SECTIONS.flatMap((section) => section.keys))];
  export const SETTINGS_BACKUP_KEY_SET = new Set(SETTINGS_BACKUP_KEYS);
  export const FAST_POLL_INTERVAL_MS = 5000;
  export const BULK_POLL_INTERVAL_MS = 30000;
  export const STATIC_POLL_INTERVAL_MS = 60000;
  export const FIRMWARE_OTA_START_QUIET_MS = 12000;
  export const FIRMWARE_OTA_INSTALL_POLL_INTERVAL_MS = 4000;
  export const CONNECTIVITY_PROBE_TIMEOUT_MS = 1500;
  export const CONNECTIVITY_PROBE_SUCCESS_TTL_MS = 30000;
  export const SUPPLEMENTARY_STATUS_REFRESH_INTERVAL_MS = 30000;
  export const LOGIN_MODAL_AUTH_STATUS_REFRESH_INTERVAL_MS = 1000;
  export const HIDDEN_POLL_INTERVAL_MS = 30000;
  export const POLL_JITTER_MIN_MS = 250;
  export const POLL_JITTER_MAX_MS = 750;
  export const FLOW_DASH_CYCLE_PX = 22;
  export const FLOW_OFFSET_PX_PER_SEC = FLOW_DASH_CYCLE_PX / 1.7;
  export const FAN_ROTATION_DEG_PER_SEC = 360 / 3.2;
export const OPENQUATT_RESUME_CLEAR_VALUE = "2000-01-01 00:00:00";
